In [14]:
!pip3 install requests

Collecting requests
  Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.7-cp312-cp312-macosx_10_13_universal2.whl.metadata (40 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
Downloading charset_normalizer-3.4.7-cp312-cp312-macosx_10_13_universal2.whl (311 kB)
Downloading idna-3.11-py3-none-any.whl (71 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests
Successfully installed certifi-2026.2.25 charset_normalizer-3.4.7 idna-3.11 requests-2.33.1 urllib3-2.6.3

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip

In [15]:
import requests
import json

In [16]:
API_KEY = "b105bbeb82cb4401899b8fbd514e8913"

In [3]:
params = {'key': API_KEY, 'page_size': 5}

In [4]:
page = requests.get('https://api.rawg.io/api/games', params=params)
page

In [5]:
res = page.json()
res

{'count': 898333,
 'next': 'https://api.rawg.io/api/games?key=b105bbeb82cb4401899b8fbd514e8913&page=2&page_size=5',
 'previous': None,
 'results': [{'id': 3498,
   'slug': 'grand-theft-auto-v',
   'name': 'Grand Theft Auto V',
   'released': '2013-09-17',
   'tba': False,
   'background_image': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg',
   'rating': 4.47,
   'rating_top': 5,
   'ratings': [{'id': 5,
     'title': 'exceptional',
     'count': 4422,
     'percent': 58.95},
    {'id': 4, 'title': 'recommended', 'count': 2462, 'percent': 32.82},
    {'id': 3, 'title': 'meh', 'count': 471, 'percent': 6.28},
    {'id': 1, 'title': 'skip', 'count': 146, 'percent': 1.95}],
   'ratings_count': 7365,
   'reviews_text_count': 74,
   'added': 22548,
   'added_by_status': {'yet': 560,
    'owned': 12877,
    'beaten': 6488,
    'toplay': 652,
    'dropped': 1192,
    'playing': 779},
   'metacritic': 92,
   'playtime': 74,
   'suggestions_count': 450,
   'updated': '2026-04-06T23:26:14',
   'user_game': None,
   'reviews_count': 7501,
   'saturated_color': '0f0f0f',
   'dominant_color': '0f0f0f',
   'platforms': [{'platform': {'id': 187,
      'name': 'PlayStation 5',
      'slug': 'playstation5',
      'image': None,
      'year_end': None,
      'year_start': 2020,
      'games_count': 1459,
      'image_background': 'https://media.rawg.io/media/games/b29/b294fdd866dcdb643e7bab370a552855.jpg'},
     'released_at': '2013-09-17',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 186,
      'name': 'Xbox Series S/X',
      'slug': 'xbox-series-x',
      'image': None,
      'year_end': None,
      'year_start': 2020,
      'games_count': 1240,
      'image_background': 'https://media.rawg.io/media/games/6cc/6cc23249972a427f697a3d10eb57a820.jpg'},
     'released_at': '2013-09-17',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 16,
      'name': 'PlayStation 3',
      'slug': 'playstation3',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 3192,
      'image_background': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg'},
     'released_at': '2013-09-17',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 4,
      'name': 'PC',
      'slug': 'pc',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 560594,
      'image_background': 'https://media.rawg.io/media/games/f87/f87457e8347484033cb34cde6101d08d.jpg'},
     'released_at': '2013-09-17',
     'requirements_en': {'minimum': 'Minimum:OS: Windows 10 64 Bit, Windows 8.1 64 Bit, Windows 8 64 Bit, Windows 7 64 Bit Service Pack 1, Windows Vista 64 Bit Service Pack 2* (*NVIDIA video card recommended if running Vista OS)Processor: Intel Core 2 Quad CPU Q6600 @ 2.40GHz (4 CPUs) / AMD Phenom 9850 Quad-Core Processor (4 CPUs) @ 2.5GHzMemory: 4 GB RAMGraphics: NVIDIA 9800 GT 1GB / AMD HD 4870 1GB (DX 10, 10.1, 11)Storage: 72 GB available spaceSound Card: 100% DirectX 10 compatibleAdditional Notes: Over time downloadable content and programming changes will change the system requirements for this game.  Please refer to your hardware manufacturer and www.rockstargames.com/support for current compatibility information. Some system components such as mobile chipsets, integrated, and AGP graphics cards may be incompatible. Unlisted specifications may not be supported by publisher.     Other requirements:  Installation and online play requires log-in to Rockstar Games Social Club (13+) network; internet connection required for activation, online play, and periodic entitlement verification; software installations required including Rockstar Games Social Club platform, DirectX , Chromium, and Microsoft Visual C++ 2008 sp1 Redistributable Package, and authentication software that recognizes certain hardware attributes for entitlement, digital rights management, system, and other support purposes.     SINGLE USE SERIAL CODE REGISTRATION VIA INTERNET REQUIRED; REGISTRATION IS LIMITED TO ONE ROCKSTAR GAMES SOCIAL CLUB ACCOUNT (13+) PER SERIAL CODE; ONLY ONE PC LOG-IN ALLOWED PER SOCIAL CLUB ACCOUNT AT ANY TIME; SERIAL CODE(S) ARE NON-TRANSFERABLE ONCE USED; SOCIAL CLUB ACCOUNTS ARE NON-TRANSFERABLE.  Partner Requirements:  Please check the terms of service of this site before purchasing this software.',
      'recommended': 'Recommended:OS: Windows 10 64 Bit, Windows 8.1 64 Bit, Windows 8 64 Bit, Windows 7 64 Bit Service Pack 1Processor: Intel Core i5 3470 @ 3.2GHz (4 CPUs) / AMD X8 FX-8350 @ 4GHz (8 CPUs)Memory: 8 GB RAMGraphics: NVIDIA GTX 660 2GB / AMD HD 7870 2GBStorage: 72 GB available spaceSound Card: 100% DirectX 10 compatibleAdditional Notes:'},
     'requirements_ru': None},
    {'platform': {'id': 18,
      'name': 'PlayStation 4',
      'slug': 'playstation4',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 6985,
      'image_background': 'https://media.rawg.io/media/games/d1a/d1a2e99ade53494c6330a0ed945fe823.jpg'},
     'released_at': '2013-09-17',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 14,
      'name': 'Xbox 360',
      'slug': 'xbox360',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 2827,
      'image_background': 'https://media.rawg.io/media/games/b8c/b8c243eaa0fbac8115e0cdccac3f91dc.jpg'},
     'released_at': '2013-09-17',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 1,
      'name': 'Xbox One',
      'slug': 'xbox-one',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 5738,
      'image_background': 'https://media.rawg.io/media/games/7cf/7cfc9220b401b7a300e409e539c9afd5.jpg'},
     'released_at': '2013-09-17',
     'requirements_en': None,
     'requirements_ru': None}],
   'parent_platforms': [{'platform': {'id': 1, 'name': 'PC', 'slug': 'pc'}},
    {'platform': {'id': 2, 'name': 'PlayStation', 'slug': 'playstation'}},
    {'platform': {'id': 3, 'name': 'Xbox', 'slug': 'xbox'}}],
   'genres': [{'id': 4,
     'name': 'Action',
     'slug': 'action',
     'games_count': 191532,
     'image_background': 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg'}],
   'stores': [{'id': 290376,
     'store': {'id': 1,
      'name': 'Steam',
      'slug': 'steam',
      'domain': 'store.steampowered.com',
      'games_count': 123274,
      'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'}},
    {'id': 290375,
     'store': {'id': 3,
      'name': 'PlayStation Store',
      'slug': 'playstation-store',
      'domain': 'store.playstation.com',
      'games_count': 8075,
      'image_background': 'https://media.rawg.io/media/games/f87/f87457e8347484033cb34cde6101d08d.jpg'}},
    {'id': 438095,
     'store': {'id': 11,
      'name': 'Epic Games',
      'slug': 'epic-games',
      'domain': 'epicgames.com',
      'games_count': 1450,
      'image_background': 'https://media.rawg.io/media/games/26d/26d4437715bee60138dab4a7c8c59c92.jpg'}},
    {'id': 290377,
     'store': {'id': 7,
      'name': 'Xbox 360 Store',
      'slug': 'xbox360',
      'domain': 'marketplace.xbox.com',
      'games_count': 1915,
      'image_background': 'https://media.rawg.io/media/games/bc0/bc06a29ceac58652b684deefe7d56099.jpg'}},
    {'id': 290378,
     'store': {'id': 2,
      'name': 'Xbox Store',
      'slug': 'xbox-store',
      'domain': 'microsoft.com',
      'games_count': 4938,
      'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'}}],
   'clip': None,
   'tags': [{'id': 31,
     'name': 'Singleplayer',
     'slug': 'singleplayer',
     'language': 'eng',
     'games_count': 250824,
     'image_background': 'https://media.rawg.io/media/games/490/49016e06ae2103881ff6373248843069.jpg'},
    {'id': 40847,
     'name': 'Steam Achievements',
     'slug': 'steam-achievements',
     'language': 'eng',
     'games_count': 51708,
     'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'},
    {'id': 7,
     'name': 'Multiplayer',
     'slug': 'multiplayer',
     'language': 'eng',
     'games_count': 42553,
     'image_background': 'https://media.rawg.io/media/games/587/587588c64afbff80e6f444eb2e46f9da.jpg'},
    {'id': 40836,
     'name': 'Full controller support',
     'slug': 'full-controller-support',
     'language': 'eng',
     'games_count': 24143,
     'image_background': 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg'},
    {'id': 13,
     'name': 'Atmospheric',
     'slug': 'atmospheric',
     'language': 'eng',
     'games_count': 39707,
     'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'},
    {'id': 42,
     'name': 'Great Soundtrack',
     'slug': 'great-soundtrack',
     'language': 'eng',
     'games_count': 3450,
     'image_background': 'https://media.rawg.io/media/games/587/587588c64afbff80e6f444eb2e46f9da.jpg'},
    {'id': 24,
     'name': 'RPG',
     'slug': 'rpg',
     'language': 'eng',
     'games_count': 26623,
     'image_background': 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg'},
    {'id': 18,
     'name': 'Co-op',
     'slug': 'co-op',
     'language': 'eng',
     'games_count': 14391,
     'image_background': 'https://media.rawg.io/media/games/511/5118aff5091cb3efec399c808f8c598f.jpg'},
    {'id': 36,
     'name': 'Open World',
     'slug': 'open-world',
     'language': 'eng',
     'games_count': 9265,
     'image_background': 'https://media.rawg.io/media/games/490/49016e06ae2103881ff6373248843069.jpg'},
    {'id': 411,
     'name': 'cooperative',
     'slug': 'cooperative',
     'language': 'eng',
     'games_count': 6588,
     'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'},
    {'id': 8,
     'name': 'First-Person',
     'slug': 'first-person',
     'language': 'eng',
     'games_count': 37393,
     'image_background': 'https://media.rawg.io/media/games/120/1201a40e4364557b124392ee50317b99.jpg'},
    {'id': 149,
     'name': 'Third Person',
     'slug': 'third-person',
     'language': 'eng',
     'games_count': 14710,
     'image_background': 'https://media.rawg.io/media/games/5c0/5c0dd63002cb23f804aab327d40ef119.jpg'},
    {'id': 4,
     'name': 'Funny',
     'slug': 'funny',
     'language': 'eng',
     'games_count': 28841,
     'image_background': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg'},
    {'id': 37,
     'name': 'Sandbox',
     'slug': 'sandbox',
     'language': 'eng',
     'games_count': 8513,
     'image_background': 'https://media.rawg.io/media/games/13a/13a528ac9cf48bbb6be5d35fe029336d.jpg'},
    {'id': 123,
     'name': 'Comedy',
     'slug': 'comedy',
     'language': 'eng',
     'games_count': 14864,
     'image_background': 'https://media.rawg.io/media/games/ffe/ffed87105b14f5beff72ff44a7793fd5.jpg'},
    {'id': 150,
     'name': 'Third-Person Shooter',
     'slug': 'third-person-shooter',
     'language': 'eng',
     'games_count': 4168,
     'image_background': 'https://media.rawg.io/media/games/f87/f87457e8347484033cb34cde6101d08d.jpg'},
    {'id': 62,
     'name': 'Moddable',
     'slug': 'moddable',
     'language': 'eng',
     'games_count': 1136,
     'image_background': 'https://media.rawg.io/media/games/d58/d588947d4286e7b5e0e12e1bea7d9844.jpg'},
    {'id': 144,
     'name': 'Crime',
     'slug': 'crime',
     'language': 'eng',
     'games_count': 3269,
     'image_background': 'https://media.rawg.io/media/games/6cc/6cc68fa183b905ac9d85efb9797776f6.jpg'},
    {'id': 62349,
     'name': 'vr mod',
     'slug': 'vr-mod',
     'language': 'eng',
     'games_count': 17,
     'image_background': 'https://media.rawg.io/media/screenshots/1bb/1bb3f78f0fe43b5d5ca2f3da5b638840.jpg'}],
   'esrb_rating': {'id': 4, 'name': 'Mature', 'slug': 'mature'},
   'short_screenshots': [{'id': -1,
     'image': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg'},
    {'id': 1827223,
     'image': 'https://media.rawg.io/media/screenshots/f95/f9518b1d99210c0cae21fc09e95b4e31.jpg'},
    {'id': 1827225,
     'image': 'https://media.rawg.io/media/screenshots/a5c/a5c95ea539c87d5f538763e16e18fb99.jpg'},
    {'id': 1827226,
     'image': 'https://media.rawg.io/media/screenshots/a7e/a7e990bc574f4d34e03b5926361d1ee7.jpg'},
    {'id': 1827228,
     'image': 'https://media.rawg.io/media/screenshots/eb0/eb0a2c0de9194a635fc0cd04f5a29ae7.jpg'},
    {'id': 1827229,
     'image': 'https://media.rawg.io/media/screenshots/ec7/ec7f05fb82290fea9647b7879fe9a6bf.jpg'},
    {'id': 1827230,
     'image': 'https://media.rawg.io/media/screenshots/260/260559fbefce0b36c66ae5e280c7d774.jpg'}]},
  {'id': 3328,
   'slug': 'the-witcher-3-wild-hunt',
   'name': 'The Witcher 3: Wild Hunt',
   'released': '2015-05-18',
   'tba': False,
   'background_image': 'https://media.rawg.io/media/games/618/618c2031a07bbff6b4f611f10b6bcdbc.jpg',
   'rating': 4.64,
   'rating_top': 5,
   'ratings': [{'id': 5,
     'title': 'exceptional',
     'count': 5585,
     'percent': 76.52},
    {'id': 4, 'title': 'recommended', 'count': 1195, 'percent': 16.37},
    {'id': 3, 'title': 'meh', 'count': 319, 'percent': 4.37},
    {'id': 1, 'title': 'skip', 'count': 200, 'percent': 2.74}],
   'ratings_count': 7180,
   'reviews_text_count': 83,
   'added': 22189,
   'added_by_status': {'yet': 1215,
    'owned': 12885,
    'beaten': 5304,
    'toplay': 856,
    'dropped': 1031,
    'playing': 898},
   'metacritic': 92,
   'playtime': 43,
   'suggestions_count': 688,
   'updated': '2026-04-06T20:17:45',
   'user_game': None,
   'reviews_count': 7299,
   'saturated_color': '0f0f0f',
   'dominant_color': '0f0f0f',
   'platforms': [{'platform': {'id': 187,
      'name': 'PlayStation 5',
      'slug': 'playstation5',
      'image': None,
      'year_end': None,
      'year_start': 2020,
      'games_count': 1459,
      'image_background': 'https://media.rawg.io/media/games/b29/b294fdd866dcdb643e7bab370a552855.jpg'},
     'released_at': '2015-05-18',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 186,
      'name': 'Xbox Series S/X',
      'slug': 'xbox-series-x',
      'image': None,
      'year_end': None,
      'year_start': 2020,
      'games_count': 1240,
      'image_background': 'https://media.rawg.io/media/games/6cc/6cc23249972a427f697a3d10eb57a820.jpg'},
     'released_at': '2015-05-18',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 5,
      'name': 'macOS',
      'slug': 'macos',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 108036,
      'image_background': 'https://media.rawg.io/media/games/46d/46d98e6910fbc0706e2948a7cc9b10c5.jpg'},
     'released_at': '2015-05-18',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 18,
      'name': 'PlayStation 4',
      'slug': 'playstation4',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 6985,
      'image_background': 'https://media.rawg.io/media/games/d1a/d1a2e99ade53494c6330a0ed945fe823.jpg'},
     'released_at': '2015-05-18',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 7,
      'name': 'Nintendo Switch',
      'slug': 'nintendo-switch',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 5767,
      'image_background': 'https://media.rawg.io/media/games/849/849414b978db37d4563ff9e4b0d3a787.jpg'},
     'released_at': '2015-05-18',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 4,
      'name': 'PC',
      'slug': 'pc',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 560594,
      'image_background': 'https://media.rawg.io/media/games/f87/f87457e8347484033cb34cde6101d08d.jpg'},
     'released_at': '2015-05-18',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 1,
      'name': 'Xbox One',
      'slug': 'xbox-one',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 5738,
      'image_background': 'https://media.rawg.io/media/games/7cf/7cfc9220b401b7a300e409e539c9afd5.jpg'},
     'released_at': '2015-05-18',
     'requirements_en': None,
     'requirements_ru': None}],
   'parent_platforms': [{'platform': {'id': 1, 'name': 'PC', 'slug': 'pc'}},
    {'platform': {'id': 2, 'name': 'PlayStation', 'slug': 'playstation'}},
    {'platform': {'id': 3, 'name': 'Xbox', 'slug': 'xbox'}},
    {'platform': {'id': 5, 'name': 'Apple Macintosh', 'slug': 'mac'}},
    {'platform': {'id': 7, 'name': 'Nintendo', 'slug': 'nintendo'}}],
   'genres': [{'id': 4,
     'name': 'Action',
     'slug': 'action',
     'games_count': 191532,
     'image_background': 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg'},
    {'id': 5,
     'name': 'RPG',
     'slug': 'role-playing-games-rpg',
     'games_count': 61944,
     'image_background': 'https://media.rawg.io/media/games/4e6/4e6e8e7f50c237d76f38f3c885dae3d2.jpg'}],
   'stores': [{'id': 354780,
     'store': {'id': 5,
      'name': 'GOG',
      'slug': 'gog',
      'domain': 'gog.com',
      'games_count': 7232,
      'image_background': 'https://media.rawg.io/media/games/be0/be01c3d7d8795a45615da139322ca080.jpg'}},
    {'id': 3565,
     'store': {'id': 3,
      'name': 'PlayStation Store',
      'slug': 'playstation-store',
      'domain': 'store.playstation.com',
      'games_count': 8075,
      'image_background': 'https://media.rawg.io/media/games/f87/f87457e8347484033cb34cde6101d08d.jpg'}},
    {'id': 305376,
     'store': {'id': 1,
      'name': 'Steam',
      'slug': 'steam',
      'domain': 'store.steampowered.com',
      'games_count': 123274,
      'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'}},
    {'id': 312313,
     'store': {'id': 2,
      'name': 'Xbox Store',
      'slug': 'xbox-store',
      'domain': 'microsoft.com',
      'games_count': 4938,
      'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'}},
    {'id': 676022,
     'store': {'id': 6,
      'name': 'Nintendo Store',
      'slug': 'nintendo',
      'domain': 'nintendo.com',
      'games_count': 9150,
      'image_background': 'https://media.rawg.io/media/games/e2d/e2d3f396b16dded0f841c17c9799a882.jpg'}}],
   'clip': None,
   'tags': [{'id': 31,
     'name': 'Singleplayer',
     'slug': 'singleplayer',
     'language': 'eng',
     'games_count': 250824,
     'image_background': 'https://media.rawg.io/media/games/490/49016e06ae2103881ff6373248843069.jpg'},
    {'id': 40836,
     'name': 'Full controller support',
     'slug': 'full-controller-support',
     'language': 'eng',
     'games_count': 24143,
     'image_background': 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg'},
    {'id': 13,
     'name': 'Atmospheric',
     'slug': 'atmospheric',
     'language': 'eng',
     'games_count': 39707,
     'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'},
    {'id': 42,
     'name': 'Great Soundtrack',
     'slug': 'great-soundtrack',
     'language': 'eng',
     'games_count': 3450,
     'image_background': 'https://media.rawg.io/media/games/587/587588c64afbff80e6f444eb2e46f9da.jpg'},
    {'id': 24,
     'name': 'RPG',
     'slug': 'rpg',
     'language': 'eng',
     'games_count': 26623,
     'image_background': 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg'},
    {'id': 118,
     'name': 'Story Rich',

In [6]:
res.keys()

dict_keys(['count', 'next', 'previous', 'results', 'seo_title', 'seo_description', 'seo_keywords', 'seo_h1', 'noindex', 'nofollow', 'description', 'filters', 'nofollow_collections'])

In [7]:
res['count']

898333

In [8]:
res['results']

[{'id': 3498,
  'slug': 'grand-theft-auto-v',
  'name': 'Grand Theft Auto V',
  'released': '2013-09-17',
  'tba': False,
  'background_image': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg',
  'rating': 4.47,
  'rating_top': 5,
  'ratings': [{'id': 5,
    'title': 'exceptional',
    'count': 4422,
    'percent': 58.95},
   {'id': 4, 'title': 'recommended', 'count': 2462, 'percent': 32.82},
   {'id': 3, 'title': 'meh', 'count': 471, 'percent': 6.28},
   {'id': 1, 'title': 'skip', 'count': 146, 'percent': 1.95}],
  'ratings_count': 7365,
  'reviews_text_count': 74,
  'added': 22548,
  'added_by_status': {'yet': 560,
   'owned': 12877,
   'beaten': 6488,
   'toplay': 652,
   'dropped': 1192,
   'playing': 779},
  'metacritic': 92,
  'playtime': 74,
  'suggestions_count': 450,
  'updated': '2026-04-06T23:26:14',
  'user_game': None,
  'reviews_count': 7501,
  'saturated_color': '0f0f0f',
  'dominant_color': '0f0f0f',
  'platforms': [{'platform': {'id': 187,
     'name': 'PlayStation 5',
     'slug': 'playstation5',
     'image': None,
     'year_end': None,
     'year_start': 2020,
     'games_count': 1459,
     'image_background': 'https://media.rawg.io/media/games/b29/b294fdd866dcdb643e7bab370a552855.jpg'},
    'released_at': '2013-09-17',
    'requirements_en': None,
    'requirements_ru': None},
   {'platform': {'id': 186,
     'name': 'Xbox Series S/X',
     'slug': 'xbox-series-x',
     'image': None,
     'year_end': None,
     'year_start': 2020,
     'games_count': 1240,
     'image_background': 'https://media.rawg.io/media/games/6cc/6cc23249972a427f697a3d10eb57a820.jpg'},
    'released_at': '2013-09-17',
    'requirements_en': None,
    'requirements_ru': None},
   {'platform': {'id': 16,
     'name': 'PlayStation 3',
     'slug': 'playstation3',
     'image': None,
     'year_end': None,
     'year_start': None,
     'games_count': 3192,
     'image_background': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg'},
    'released_at': '2013-09-17',
    'requirements_en': None,
    'requirements_ru': None},
   {'platform': {'id': 4,
     'name': 'PC',
     'slug': 'pc',
     'image': None,
     'year_end': None,
     'year_start': None,
     'games_count': 560594,
     'image_background': 'https://media.rawg.io/media/games/f87/f87457e8347484033cb34cde6101d08d.jpg'},
    'released_at': '2013-09-17',
    'requirements_en': {'minimum': 'Minimum:OS: Windows 10 64 Bit, Windows 8.1 64 Bit, Windows 8 64 Bit, Windows 7 64 Bit Service Pack 1, Windows Vista 64 Bit Service Pack 2* (*NVIDIA video card recommended if running Vista OS)Processor: Intel Core 2 Quad CPU Q6600 @ 2.40GHz (4 CPUs) / AMD Phenom 9850 Quad-Core Processor (4 CPUs) @ 2.5GHzMemory: 4 GB RAMGraphics: NVIDIA 9800 GT 1GB / AMD HD 4870 1GB (DX 10, 10.1, 11)Storage: 72 GB available spaceSound Card: 100% DirectX 10 compatibleAdditional Notes: Over time downloadable content and programming changes will change the system requirements for this game.  Please refer to your hardware manufacturer and www.rockstargames.com/support for current compatibility information. Some system components such as mobile chipsets, integrated, and AGP graphics cards may be incompatible. Unlisted specifications may not be supported by publisher.     Other requirements:  Installation and online play requires log-in to Rockstar Games Social Club (13+) network; internet connection required for activation, online play, and periodic entitlement verification; software installations required including Rockstar Games Social Club platform, DirectX , Chromium, and Microsoft Visual C++ 2008 sp1 Redistributable Package, and authentication software that recognizes certain hardware attributes for entitlement, digital rights management, system, and other support purposes.     SINGLE USE SERIAL CODE REGISTRATION VIA INTERNET REQUIRED; REGISTRATION IS LIMITED TO ONE ROCKSTAR GAMES SOCIAL CLUB ACCOUNT (13+) PER SERIAL CODE; ONLY ONE PC LOG-IN ALLOWED PER SOCIAL CLUB ACCOUNT AT ANY TIME; SERIAL CODE(S) ARE NON-TRANSFERABLE ONCE USED; SOCIAL CLUB ACCOUNTS ARE NON-TRANSFERABLE.  Partner Requirements:  Please check the terms of service of this site before purchasing this software.',
     'recommended': 'Recommended:OS: Windows 10 64 Bit, Windows 8.1 64 Bit, Windows 8 64 Bit, Windows 7 64 Bit Service Pack 1Processor: Intel Core i5 3470 @ 3.2GHz (4 CPUs) / AMD X8 FX-8350 @ 4GHz (8 CPUs)Memory: 8 GB RAMGraphics: NVIDIA GTX 660 2GB / AMD HD 7870 2GBStorage: 72 GB available spaceSound Card: 100% DirectX 10 compatibleAdditional Notes:'},
    'requirements_ru': None},
   {'platform': {'id': 18,
     'name': 'PlayStation 4',
     'slug': 'playstation4',
     'image': None,
     'year_end': None,
     'year_start': None,
     'games_count': 6985,
     'image_background': 'https://media.rawg.io/media/games/d1a/d1a2e99ade53494c6330a0ed945fe823.jpg'},
    'released_at': '2013-09-17',
    'requirements_en': None,
    'requirements_ru': None},
   {'platform': {'id': 14,
     'name': 'Xbox 360',
     'slug': 'xbox360',
     'image': None,
     'year_end': None,
     'year_start': None,
     'games_count': 2827,
     'image_background': 'https://media.rawg.io/media/games/b8c/b8c243eaa0fbac8115e0cdccac3f91dc.jpg'},
    'released_at': '2013-09-17',
    'requirements_en': None,
    'requirements_ru': None},
   {'platform': {'id': 1,
     'name': 'Xbox One',
     'slug': 'xbox-one',
     'image': None,
     'year_end': None,
     'year_start': None,
     'games_count': 5738,
     'image_background': 'https://media.rawg.io/media/games/7cf/7cfc9220b401b7a300e409e539c9afd5.jpg'},
    'released_at': '2013-09-17',
    'requirements_en': None,
    'requirements_ru': None}],
  'parent_platforms': [{'platform': {'id': 1, 'name': 'PC', 'slug': 'pc'}},
   {'platform': {'id': 2, 'name': 'PlayStation', 'slug': 'playstation'}},
   {'platform': {'id': 3, 'name': 'Xbox', 'slug': 'xbox'}}],
  'genres': [{'id': 4,
    'name': 'Action',
    'slug': 'action',
    'games_count': 191532,
    'image_background': 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg'}],
  'stores': [{'id': 290376,
    'store': {'id': 1,
     'name': 'Steam',
     'slug': 'steam',
     'domain': 'store.steampowered.com',
     'games_count': 123274,
     'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'}},
   {'id': 290375,
    'store': {'id': 3,
     'name': 'PlayStation Store',
     'slug': 'playstation-store',
     'domain': 'store.playstation.com',
     'games_count': 8075,
     'image_background': 'https://media.rawg.io/media/games/f87/f87457e8347484033cb34cde6101d08d.jpg'}},
   {'id': 438095,
    'store': {'id': 11,
     'name': 'Epic Games',
     'slug': 'epic-games',
     'domain': 'epicgames.com',
     'games_count': 1450,
     'image_background': 'https://media.rawg.io/media/games/26d/26d4437715bee60138dab4a7c8c59c92.jpg'}},
   {'id': 290377,
    'store': {'id': 7,
     'name': 'Xbox 360 Store',
     'slug': 'xbox360',
     'domain': 'marketplace.xbox.com',
     'games_count': 1915,
     'image_background': 'https://media.rawg.io/media/games/bc0/bc06a29ceac58652b684deefe7d56099.jpg'}},
   {'id': 290378,
    'store': {'id': 2,
     'name': 'Xbox Store',
     'slug': 'xbox-store',
     'domain': 'microsoft.com',
     'games_count': 4938,
     'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'}}],
  'clip': None,
  'tags': [{'id': 31,
    'name': 'Singleplayer',
    'slug': 'singleplayer',
    'language': 'eng',
    'games_count': 250824,
    'image_background': 'https://media.rawg.io/media/games/490/49016e06ae2103881ff6373248843069.jpg'},
   {'id': 40847,
    'name': 'Steam Achievements',
    'slug': 'steam-achievements',
    'language': 'eng',
    'games_count': 51708,
    'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'},
   {'id': 7,
    'name': 'Multiplayer',
    'slug': 'multiplayer',
    'language': 'eng',
    'games_count': 42553,
    'image_background': 'https://media.rawg.io/media/games/587/587588c64afbff80e6f444eb2e46f9da.jpg'},
   {'id': 40836,
    'name': 'Full controller support',
    'slug': 'full-controller-support',
    'language': 'eng',
    'games_count': 24143,
    'image_background': 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg'},
   {'id': 13,
    'name': 'Atmospheric',
    'slug': 'atmospheric',
    'language': 'eng',
    'games_count': 39707,
    'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'},
   {'id': 42,
    'name': 'Great Soundtrack',
    'slug': 'great-soundtrack',
    'language': 'eng',
    'games_count': 3450,
    'image_background': 'https://media.rawg.io/media/games/587/587588c64afbff80e6f444eb2e46f9da.jpg'},
   {'id': 24,
    'name': 'RPG',
    'slug': 'rpg',
    'language': 'eng',
    'games_count': 26623,
    'image_background': 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg'},
   {'id': 18,
    'name': 'Co-op',
    'slug': 'co-op',
    'language': 'eng',
    'games_count': 14391,
    'image_background': 'https://media.rawg.io/media/games/511/5118aff5091cb3efec399c808f8c598f.jpg'},
   {'id': 36,
    'name': 'Open World',
    'slug': 'open-world',
    'language': 'eng',
    'games_count': 9265,
    'image_background': 'https://media.rawg.io/media/games/490/49016e06ae2103881ff6373248843069.jpg'},
   {'id': 411,
    'name': 'cooperative',
    'slug': 'cooperative',
    'language': 'eng',
    'games_count': 6588,
    'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'},
   {'id': 8,
    'name': 'First-Person',
    'slug': 'first-person',
    'language': 'eng',
    'games_count': 37393,
    'image_background': 'https://media.rawg.io/media/games/120/1201a40e4364557b124392ee50317b99.jpg'},
   {'id': 149,
    'name': 'Third Person',
    'slug': 'third-person',
    'language': 'eng',
    'games_count': 14710,
    'image_background': 'https://media.rawg.io/media/games/5c0/5c0dd63002cb23f804aab327d40ef119.jpg'},
   {'id': 4,
    'name': 'Funny',
    'slug': 'funny',
    'language': 'eng',
    'games_count': 28841,
    'image_background': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg'},
   {'id': 37,
    'name': 'Sandbox',
    'slug': 'sandbox',
    'language': 'eng',
    'games_count': 8513,
    'image_background': 'https://media.rawg.io/media/games/13a/13a528ac9cf48bbb6be5d35fe029336d.jpg'},
   {'id': 123,
    'name': 'Comedy',
    'slug': 'comedy',
    'language': 'eng',
    'games_count': 14864,
    'image_background': 'https://media.rawg.io/media/games/ffe/ffed87105b14f5beff72ff44a7793fd5.jpg'},
   {'id': 150,
    'name': 'Third-Person Shooter',
    'slug': 'third-person-shooter',
    'language': 'eng',
    'games_count': 4168,
    'image_background': 'https://media.rawg.io/media/games/f87/f87457e8347484033cb34cde6101d08d.jpg'},
   {'id': 62,
    'name': 'Moddable',
    'slug': 'moddable',
    'language': 'eng',
    'games_count': 1136,
    'image_background': 'https://media.rawg.io/media/games/d58/d588947d4286e7b5e0e12e1bea7d9844.jpg'},
   {'id': 144,
    'name': 'Crime',
    'slug': 'crime',
    'language': 'eng',
    'games_count': 3269,
    'image_background': 'https://media.rawg.io/media/games/6cc/6cc68fa183b905ac9d85efb9797776f6.jpg'},
   {'id': 62349,
    'name': 'vr mod',
    'slug': 'vr-mod',
    'language': 'eng',
    'games_count': 17,
    'image_background': 'https://media.rawg.io/media/screenshots/1bb/1bb3f78f0fe43b5d5ca2f3da5b638840.jpg'}],
  'esrb_rating': {'id': 4, 'name': 'Mature', 'slug': 'mature'},
  'short_screenshots': [{'id': -1,
    'image': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg'},
   {'id': 1827223,
    'image': 'https://media.rawg.io/media/screenshots/f95/f9518b1d99210c0cae21fc09e95b4e31.jpg'},
   {'id': 1827225,
    'image': 'https://media.rawg.io/media/screenshots/a5c/a5c95ea539c87d5f538763e16e18fb99.jpg'},
   {'id': 1827226,
    'image': 'https://media.rawg.io/media/screenshots/a7e/a7e990bc574f4d34e03b5926361d1ee7.jpg'},
   {'id': 1827228,
    'image': 'https://media.rawg.io/media/screenshots/eb0/eb0a2c0de9194a635fc0cd04f5a29ae7.jpg'},
   {'id': 1827229,
    'image': 'https://media.rawg.io/media/screenshots/ec7/ec7f05fb82290fea9647b7879fe9a6bf.jpg'},
   {'id': 1827230,
    'image': 'https://media.rawg.io/media/screenshots/260/260559fbefce0b36c66ae5e280c7d774.jpg'}]},
 {'id': 3328,
  'slug': 'the-witcher-3-wild-hunt',
  'name': 'The Witcher 3: Wild Hunt',
  'released': '2015-05-18',
  'tba': False,
  'background_image': 'https://media.rawg.io/media/games/618/618c2031a07bbff6b4f611f10b6bcdbc.jpg',
  'rating': 4.64,
  'rating_top': 5,
  'ratings': [{'id': 5,
    'title': 'exceptional',
    'count': 5585,
    'percent': 76.52},
   {'id': 4, 'title': 'recommended', 'count': 1195, 'percent': 16.37},
   {'id': 3, 'title': 'meh', 'count': 319, 'percent': 4.37},
   {'id': 1, 'title': 'skip', 'count': 200, 'percent': 2.74}],
  'ratings_count': 7180,
  'reviews_text_count': 83,
  'added': 22189,
  'added_by_status': {'yet': 1215,
   'owned': 12885,
   'beaten': 5304,
   'toplay': 856,
   'dropped': 1031,
   'playing': 898},
  'metacritic': 92,
  'playtime': 43,
  'suggestions_count': 688,
  'updated': '2026-04-06T20:17:45',
  'user_game': None,
  'reviews_count': 7299,
  'saturated_color': '0f0f0f',
  'dominant_color': '0f0f0f',
  'platforms': [{'platform': {'id': 187,
     'name': 'PlayStation 5',
     'slug': 'playstation5',
     'image': None,
     'year_end': None,
     'year_start': 2020,
     'games_count': 1459,
     'image_background': 'https://media.rawg.io/media/games/b29/b294fdd866dcdb643e7bab370a552855.jpg'},
    'released_at': '2015-05-18',
    'requirements_en': None,
    'requirements_ru': None},
   {'platform': {'id': 186,
     'name': 'Xbox Series S/X',
     'slug': 'xbox-series-x',
     'image': None,
     'year_end': None,
     'year_start': 2020,
     'games_count': 1240,
     'image_background': 'https://media.rawg.io/media/games/6cc/6cc23249972a427f697a3d10eb57a820.jpg'},
    'released_at': '2015-05-18',
    'requirements_en': None,
    'requirements_ru': None},
   {'platform': {'id': 5,
     'name': 'macOS',
     'slug': 'macos',
     'image': None,
     'year_end': None,
     'year_start': None,
     'games_count': 108036,
     'image_background': 'https://media.rawg.io/media/games/46d/46d98e6910fbc0706e2948a7cc9b10c5.jpg'},
    'released_at': '2015-05-18',
    'requirements_en': None,
    'requirements_ru': None},
   {'platform': {'id': 18,
     'name': 'PlayStation 4',
     'slug': 'playstation4',
     'image': None,
     'year_end': None,
     'year_start': None,
     'games_count': 6985,
     'image_background': 'https://media.rawg.io/media/games/d1a/d1a2e99ade53494c6330a0ed945fe823.jpg'},
    'released_at': '2015-05-18',
    'requirements_en': None,
    'requirements_ru': None},
   {'platform': {'id': 7,
     'name': 'Nintendo Switch',
     'slug': 'nintendo-switch',
     'image': None,
     'year_end': None,
     'year_start': None,
     'games_count': 5767,
     'image_background': 'https://media.rawg.io/media/games/849/849414b978db37d4563ff9e4b0d3a787.jpg'},
    'released_at': '2015-05-18',
    'requirements_en': None,
    'requirements_ru': None},
   {'platform': {'id': 4,
     'name': 'PC',
     'slug': 'pc',
     'image': None,
     'year_end': None,
     'year_start': None,
     'games_count': 560594,
     'image_background': 'https://media.rawg.io/media/games/f87/f87457e8347484033cb34cde6101d08d.jpg'},
    'released_at': '2015-05-18',
    'requirements_en': None,
    'requirements_ru': None},
   {'platform': {'id': 1,
     'name': 'Xbox One',
     'slug': 'xbox-one',
     'image': None,
     'year_end': None,
     'year_start': None,
     'games_count': 5738,
     'image_background': 'https://media.rawg.io/media/games/7cf/7cfc9220b401b7a300e409e539c9afd5.jpg'},
    'released_at': '2015-05-18',
    'requirements_en': None,
    'requirements_ru': None}],
  'parent_platforms': [{'platform': {'id': 1, 'name': 'PC', 'slug': 'pc'}},
   {'platform': {'id': 2, 'name': 'PlayStation', 'slug': 'playstation'}},
   {'platform': {'id': 3, 'name': 'Xbox', 'slug': 'xbox'}},
   {'platform': {'id': 5, 'name': 'Apple Macintosh', 'slug': 'mac'}},
   {'platform': {'id': 7, 'name': 'Nintendo', 'slug': 'nintendo'}}],
  'genres': [{'id': 4,
    'name': 'Action',
    'slug': 'action',
    'games_count': 191532,
    'image_background': 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg'},
   {'id': 5,
    'name': 'RPG',
    'slug': 'role-playing-games-rpg',
    'games_count': 61944,
    'image_background': 'https://media.rawg.io/media/games/4e6/4e6e8e7f50c237d76f38f3c885dae3d2.jpg'}],
  'stores': [{'id': 354780,
    'store': {'id': 5,
     'name': 'GOG',
     'slug': 'gog',
     'domain': 'gog.com',
     'games_count': 7232,
     'image_background': 'https://media.rawg.io/media/games/be0/be01c3d7d8795a45615da139322ca080.jpg'}},
   {'id': 3565,
    'store': {'id': 3,
     'name': 'PlayStation Store',
     'slug': 'playstation-store',
     'domain': 'store.playstation.com',
     'games_count': 8075,
     'image_background': 'https://media.rawg.io/media/games/f87/f87457e8347484033cb34cde6101d08d.jpg'}},
   {'id': 305376,
    'store': {'id': 1,
     'name': 'Steam',
     'slug': 'steam',
     'domain': 'store.steampowered.com',
     'games_count': 123274,
     'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'}},
   {'id': 312313,
    'store': {'id': 2,
     'name': 'Xbox Store',
     'slug': 'xbox-store',
     'domain': 'microsoft.com',
     'games_count': 4938,
     'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'}},
   {'id': 676022,
    'store': {'id': 6,
     'name': 'Nintendo Store',
     'slug': 'nintendo',
     'domain': 'nintendo.com',
     'games_count': 9150,
     'image_background': 'https://media.rawg.io/media/games/e2d/e2d3f396b16dded0f841c17c9799a882.jpg'}}],
  'clip': None,
  'tags': [{'id': 31,
    'name': 'Singleplayer',
    'slug': 'singleplayer',
    'language': 'eng',
    'games_count': 250824,
    'image_background': 'https://media.rawg.io/media/games/490/49016e06ae2103881ff6373248843069.jpg'},
   {'id': 40836,
    'name': 'Full controller support',
    'slug': 'full-controller-support',
    'language': 'eng',
    'games_count': 24143,
    'image_background': 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg'},
   {'id': 13,
    'name': 'Atmospheric',
    'slug': 'atmospheric',
    'language': 'eng',
    'games_count': 39707,
    'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'},
   {'id': 42,
    'name': 'Great Soundtrack',
    'slug': 'great-soundtrack',
    'language': 'eng',
    'games_count': 3450,
    'image_background': 'https://media.rawg.io/media/games/587/587588c64afbff80e6f444eb2e46f9da.jpg'},
   {'id': 24,
    'name': 'RPG',
    'slug': 'rpg',
    'language': 'eng',
    'games_count': 26623,
    'image_background': 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg'},
   {'id': 118,
    'name': 'Story Rich',
    'slug': 'story-rich',
    'language': 'eng',
    'games_count': 27258,
    'image_background': 'https://media.rawg.io/media/games/ee3/ee3e10193aafc3230ba1cae426967d10.jpg'},
   {'id': 36,
    'name': 'Open World',
    'slug': 'open-world',
    'language': 'eng',
    'games_count': 9265,
    'image_background': 'https://media.rawg.io/media/games/490/49016e06ae2103881ff6373248843069.jpg'},
   {'id': 149,
    'name': 'Third Person',
    'slug': 'third-person',
    'language': 'eng',
    'games_count': 14710,
    'image_background': 'https://media.rawg.io/media/games/5c0/5c0dd63002cb23f804aab327d40ef119.jpg'},

In [9]:
res['results'][0]

{'id': 3498,
 'slug': 'grand-theft-auto-v',
 'name': 'Grand Theft Auto V',
 'released': '2013-09-17',
 'tba': False,
 'background_image': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg',
 'rating': 4.47,
 'rating_top': 5,
 'ratings': [{'id': 5,
   'title': 'exceptional',
   'count': 4422,
   'percent': 58.95},
  {'id': 4, 'title': 'recommended', 'count': 2462, 'percent': 32.82},
  {'id': 3, 'title': 'meh', 'count': 471, 'percent': 6.28},
  {'id': 1, 'title': 'skip', 'count': 146, 'percent': 1.95}],
 'ratings_count': 7365,
 'reviews_text_count': 74,
 'added': 22548,
 'added_by_status': {'yet': 560,
  'owned': 12877,
  'beaten': 6488,
  'toplay': 652,
  'dropped': 1192,
  'playing': 779},
 'metacritic': 92,
 'playtime': 74,
 'suggestions_count': 450,
 'updated': '2026-04-06T23:26:14',
 'user_game': None,
 'reviews_count': 7501,
 'saturated_color': '0f0f0f',
 'dominant_color': '0f0f0f',
 'platforms': [{'platform': {'id': 187,
    'name': 'PlayStation 5',
    'slug': 'playstation5',
    'image': None,
    'year_end': None,
    'year_start': 2020,
    'games_count': 1459,
    'image_background': 'https://media.rawg.io/media/games/b29/b294fdd866dcdb643e7bab370a552855.jpg'},
   'released_at': '2013-09-17',
   'requirements_en': None,
   'requirements_ru': None},
  {'platform': {'id': 186,
    'name': 'Xbox Series S/X',
    'slug': 'xbox-series-x',
    'image': None,
    'year_end': None,
    'year_start': 2020,
    'games_count': 1240,
    'image_background': 'https://media.rawg.io/media/games/6cc/6cc23249972a427f697a3d10eb57a820.jpg'},
   'released_at': '2013-09-17',
   'requirements_en': None,
   'requirements_ru': None},
  {'platform': {'id': 16,
    'name': 'PlayStation 3',
    'slug': 'playstation3',
    'image': None,
    'year_end': None,
    'year_start': None,
    'games_count': 3192,
    'image_background': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg'},
   'released_at': '2013-09-17',
   'requirements_en': None,
   'requirements_ru': None},
  {'platform': {'id': 4,
    'name': 'PC',
    'slug': 'pc',
    'image': None,
    'year_end': None,
    'year_start': None,
    'games_count': 560594,
    'image_background': 'https://media.rawg.io/media/games/f87/f87457e8347484033cb34cde6101d08d.jpg'},
   'released_at': '2013-09-17',
   'requirements_en': {'minimum': 'Minimum:OS: Windows 10 64 Bit, Windows 8.1 64 Bit, Windows 8 64 Bit, Windows 7 64 Bit Service Pack 1, Windows Vista 64 Bit Service Pack 2* (*NVIDIA video card recommended if running Vista OS)Processor: Intel Core 2 Quad CPU Q6600 @ 2.40GHz (4 CPUs) / AMD Phenom 9850 Quad-Core Processor (4 CPUs) @ 2.5GHzMemory: 4 GB RAMGraphics: NVIDIA 9800 GT 1GB / AMD HD 4870 1GB (DX 10, 10.1, 11)Storage: 72 GB available spaceSound Card: 100% DirectX 10 compatibleAdditional Notes: Over time downloadable content and programming changes will change the system requirements for this game.  Please refer to your hardware manufacturer and www.rockstargames.com/support for current compatibility information. Some system components such as mobile chipsets, integrated, and AGP graphics cards may be incompatible. Unlisted specifications may not be supported by publisher.     Other requirements:  Installation and online play requires log-in to Rockstar Games Social Club (13+) network; internet connection required for activation, online play, and periodic entitlement verification; software installations required including Rockstar Games Social Club platform, DirectX , Chromium, and Microsoft Visual C++ 2008 sp1 Redistributable Package, and authentication software that recognizes certain hardware attributes for entitlement, digital rights management, system, and other support purposes.     SINGLE USE SERIAL CODE REGISTRATION VIA INTERNET REQUIRED; REGISTRATION IS LIMITED TO ONE ROCKSTAR GAMES SOCIAL CLUB ACCOUNT (13+) PER SERIAL CODE; ONLY ONE PC LOG-IN ALLOWED PER SOCIAL CLUB ACCOUNT AT ANY TIME; SERIAL CODE(S) ARE NON-TRANSFERABLE ONCE USED; SOCIAL CLUB ACCOUNTS ARE NON-TRANSFERABLE.  Partner Requirements:  Please check the terms of service of this site before purchasing this software.',
    'recommended': 'Recommended:OS: Windows 10 64 Bit, Windows 8.1 64 Bit, Windows 8 64 Bit, Windows 7 64 Bit Service Pack 1Processor: Intel Core i5 3470 @ 3.2GHz (4 CPUs) / AMD X8 FX-8350 @ 4GHz (8 CPUs)Memory: 8 GB RAMGraphics: NVIDIA GTX 660 2GB / AMD HD 7870 2GBStorage: 72 GB available spaceSound Card: 100% DirectX 10 compatibleAdditional Notes:'},
   'requirements_ru': None},
  {'platform': {'id': 18,
    'name': 'PlayStation 4',
    'slug': 'playstation4',
    'image': None,
    'year_end': None,
    'year_start': None,
    'games_count': 6985,
    'image_background': 'https://media.rawg.io/media/games/d1a/d1a2e99ade53494c6330a0ed945fe823.jpg'},
   'released_at': '2013-09-17',
   'requirements_en': None,
   'requirements_ru': None},
  {'platform': {'id': 14,
    'name': 'Xbox 360',
    'slug': 'xbox360',
    'image': None,
    'year_end': None,
    'year_start': None,
    'games_count': 2827,
    'image_background': 'https://media.rawg.io/media/games/b8c/b8c243eaa0fbac8115e0cdccac3f91dc.jpg'},
   'released_at': '2013-09-17',
   'requirements_en': None,
   'requirements_ru': None},
  {'platform': {'id': 1,
    'name': 'Xbox One',
    'slug': 'xbox-one',
    'image': None,
    'year_end': None,
    'year_start': None,
    'games_count': 5738,
    'image_background': 'https://media.rawg.io/media/games/7cf/7cfc9220b401b7a300e409e539c9afd5.jpg'},
   'released_at': '2013-09-17',
   'requirements_en': None,
   'requirements_ru': None}],
 'parent_platforms': [{'platform': {'id': 1, 'name': 'PC', 'slug': 'pc'}},
  {'platform': {'id': 2, 'name': 'PlayStation', 'slug': 'playstation'}},
  {'platform': {'id': 3, 'name': 'Xbox', 'slug': 'xbox'}}],
 'genres': [{'id': 4,
   'name': 'Action',
   'slug': 'action',
   'games_count': 191532,
   'image_background': 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg'}],
 'stores': [{'id': 290376,
   'store': {'id': 1,
    'name': 'Steam',
    'slug': 'steam',
    'domain': 'store.steampowered.com',
    'games_count': 123274,
    'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'}},
  {'id': 290375,
   'store': {'id': 3,
    'name': 'PlayStation Store',
    'slug': 'playstation-store',
    'domain': 'store.playstation.com',
    'games_count': 8075,
    'image_background': 'https://media.rawg.io/media/games/f87/f87457e8347484033cb34cde6101d08d.jpg'}},
  {'id': 438095,
   'store': {'id': 11,
    'name': 'Epic Games',
    'slug': 'epic-games',
    'domain': 'epicgames.com',
    'games_count': 1450,
    'image_background': 'https://media.rawg.io/media/games/26d/26d4437715bee60138dab4a7c8c59c92.jpg'}},
  {'id': 290377,
   'store': {'id': 7,
    'name': 'Xbox 360 Store',
    'slug': 'xbox360',
    'domain': 'marketplace.xbox.com',
    'games_count': 1915,
    'image_background': 'https://media.rawg.io/media/games/bc0/bc06a29ceac58652b684deefe7d56099.jpg'}},
  {'id': 290378,
   'store': {'id': 2,
    'name': 'Xbox Store',
    'slug': 'xbox-store',
    'domain': 'microsoft.com',
    'games_count': 4938,
    'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'}}],
 'clip': None,
 'tags': [{'id': 31,
   'name': 'Singleplayer',
   'slug': 'singleplayer',
   'language': 'eng',
   'games_count': 250824,
   'image_background': 'https://media.rawg.io/media/games/490/49016e06ae2103881ff6373248843069.jpg'},
  {'id': 40847,
   'name': 'Steam Achievements',
   'slug': 'steam-achievements',
   'language': 'eng',
   'games_count': 51708,
   'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'},
  {'id': 7,
   'name': 'Multiplayer',
   'slug': 'multiplayer',
   'language': 'eng',
   'games_count': 42553,
   'image_background': 'https://media.rawg.io/media/games/587/587588c64afbff80e6f444eb2e46f9da.jpg'},
  {'id': 40836,
   'name': 'Full controller support',
   'slug': 'full-controller-support',
   'language': 'eng',
   'games_count': 24143,
   'image_background': 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg'},
  {'id': 13,
   'name': 'Atmospheric',
   'slug': 'atmospheric',
   'language': 'eng',
   'games_count': 39707,
   'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'},
  {'id': 42,
   'name': 'Great Soundtrack',
   'slug': 'great-soundtrack',
   'language': 'eng',
   'games_count': 3450,
   'image_background': 'https://media.rawg.io/media/games/587/587588c64afbff80e6f444eb2e46f9da.jpg'},
  {'id': 24,
   'name': 'RPG',
   'slug': 'rpg',
   'language': 'eng',
   'games_count': 26623,
   'image_background': 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg'},
  {'id': 18,
   'name': 'Co-op',
   'slug': 'co-op',
   'language': 'eng',
   'games_count': 14391,
   'image_background': 'https://media.rawg.io/media/games/511/5118aff5091cb3efec399c808f8c598f.jpg'},
  {'id': 36,
   'name': 'Open World',
   'slug': 'open-world',
   'language': 'eng',
   'games_count': 9265,
   'image_background': 'https://media.rawg.io/media/games/490/49016e06ae2103881ff6373248843069.jpg'},
  {'id': 411,
   'name': 'cooperative',
   'slug': 'cooperative',
   'language': 'eng',
   'games_count': 6588,
   'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'},
  {'id': 8,
   'name': 'First-Person',
   'slug': 'first-person',
   'language': 'eng',
   'games_count': 37393,
   'image_background': 'https://media.rawg.io/media/games/120/1201a40e4364557b124392ee50317b99.jpg'},
  {'id': 149,
   'name': 'Third Person',
   'slug': 'third-person',
   'language': 'eng',
   'games_count': 14710,
   'image_background': 'https://media.rawg.io/media/games/5c0/5c0dd63002cb23f804aab327d40ef119.jpg'},
  {'id': 4,
   'name': 'Funny',
   'slug': 'funny',
   'language': 'eng',
   'games_count': 28841,
   'image_background': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg'},
  {'id': 37,
   'name': 'Sandbox',
   'slug': 'sandbox',
   'language': 'eng',
   'games_count': 8513,
   'image_background': 'https://media.rawg.io/media/games/13a/13a528ac9cf48bbb6be5d35fe029336d.jpg'},
  {'id': 123,
   'name': 'Comedy',
   'slug': 'comedy',
   'language': 'eng',
   'games_count': 14864,
   'image_background': 'https://media.rawg.io/media/games/ffe/ffed87105b14f5beff72ff44a7793fd5.jpg'},
  {'id': 150,
   'name': 'Third-Person Shooter',
   'slug': 'third-person-shooter',
   'language': 'eng',
   'games_count': 4168,
   'image_background': 'https://media.rawg.io/media/games/f87/f87457e8347484033cb34cde6101d08d.jpg'},
  {'id': 62,
   'name': 'Moddable',
   'slug': 'moddable',
   'language': 'eng',
   'games_count': 1136,
   'image_background': 'https://media.rawg.io/media/games/d58/d588947d4286e7b5e0e12e1bea7d9844.jpg'},
  {'id': 144,
   'name': 'Crime',
   'slug': 'crime',
   'language': 'eng',
   'games_count': 3269,
   'image_background': 'https://media.rawg.io/media/games/6cc/6cc68fa183b905ac9d85efb9797776f6.jpg'},
  {'id': 62349,
   'name': 'vr mod',
   'slug': 'vr-mod',
   'language': 'eng',
   'games_count': 17,
   'image_background': 'https://media.rawg.io/media/screenshots/1bb/1bb3f78f0fe43b5d5ca2f3da5b638840.jpg'}],
 'esrb_rating': {'id': 4, 'name': 'Mature', 'slug': 'mature'},
 'short_screenshots': [{'id': -1,
   'image': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg'},
  {'id': 1827223,
   'image': 'https://media.rawg.io/media/screenshots/f95/f9518b1d99210c0cae21fc09e95b4e31.jpg'},
  {'id': 1827225,
   'image': 'https://media.rawg.io/media/screenshots/a5c/a5c95ea539c87d5f538763e16e18fb99.jpg'},
  {'id': 1827226,
   'image': 'https://media.rawg.io/media/screenshots/a7e/a7e990bc574f4d34e03b5926361d1ee7.jpg'},
  {'id': 1827228,
   'image': 'https://media.rawg.io/media/screenshots/eb0/eb0a2c0de9194a635fc0cd04f5a29ae7.jpg'},
  {'id': 1827229,
   'image': 'https://media.rawg.io/media/screenshots/ec7/ec7f05fb82290fea9647b7879fe9a6bf.jpg'},
  {'id': 1827230,
   'image': 'https://media.rawg.io/media/screenshots/260/260559fbefce0b36c66ae5e280c7d774.jpg'}]}

In [6]:
!pip3 install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp312-cp312-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/zolzaya/Library/Python/3.12/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/zolzaya/Library/Python/3.12/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 1.1 MB/s eta 0:00:0000:0100:010m
Downloading numpy-2.4.4-cp312-cp312-macosx_14_0_arm64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 2.3 MB/s eta 0:00:00a 0:00:01
Installing collected packages: numpy, pandas
Successfully installed numpy-2.4.4 pandas-3.0.2

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip

чтобы загрузить спарсенные данные(games5.csv) пришлось переключить kernel с Colab на локальный Python 3.12 тк Colab не имеет доступа к локальным файлам. после переключения пришлось установить пандас вручную тк окружение не содержит предустановленных библиотек

In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame(res['results'])
df

NameError: name 'res' is not defined

мы в общем долго думали шо как объединить эти данные со скраппингом. пришли к выводу, что самое логичное это по сути обогатить имеющиеся данные новыми признаками. то есть пройтись по играм, которые собрали на этапе веб скраппинга, и добавить к ним новых свойчтв. вот, на этапе еда глянем какие признаки точно оставляем, какие по итогу не очень большую ценность несут

In [9]:
df_s = pd.read_csv('games5.csv')
df_s

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,https://store.steampowered.com/app/730/Counter...,Counter-Strike 2,2012-08-21,Valve,"['Action', 'Free To Play']",Free To Play,0%,1.0,"['FPS', 'Shooter', 'Multiplayer', 'Competitive...",Very Positive,"9,521,157",Mostly Positive,"94,756"
1,https://store.steampowered.com/app/3321460/Cri...,Crimson Desert,NaN,Pearl Abyss,"['Экшены', 'Приключенческие игры']","69,99€",0%,1.0,"['Открытый мир', 'Экшен', 'Для одного игрока',...",Очень положительные,78 700,NaN,NaN
2,https://store.steampowered.com/app/2868840/Sla...,Slay the Spire 2,2026-03-05,Mega Crit,"['Indie', 'Strategy', 'Early Access']","22,99€",0%,0.0,"['Strategy', 'Roguelike', 'Card Game', 'Deckbu...",Very Positive,"98,132",Mostly Positive,"85,557"
3,https://store.steampowered.com/app/2050650/Res...,Resident Evil 4,2023-03-24,"CAPCOM Co., Ltd.","['Action', 'Adventure']","100,24€",-60%,27.0,"['Horror', 'Action', 'Survival Horror', 'Third...",Overwhelmingly Positive,"157,050",Overwhelmingly Positive,"7,371"
4,https://store.steampowered.com/app/1172470/Ape...,Apex Legends™,2020-11-04,Respawn,"['Action', 'Adventure', 'Free To Play']",Free To Play,0%,0.0,"['Free to Play', 'Battle Royale', 'Multiplayer...",Mixed,"1,040,934",Mixed,"8,265"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11020,https://store.steampowered.com/app/760070/Imme...,Immersion Pack - Europa Universalis IV: Rule B...,2018-03-20,Paradox Development Studio,"['Simulation', 'Strategy']","9,99€",NaN,0.0,"['Strategy', 'Simulation', 'Historical', 'Gran...",NaN,NaN,NaN,NaN
11021,https://store.steampowered.com/app/1497230/Cau...,Cauldrons of War - Stalingrad,2021-09-10,Maestro Cinetik,['Strategy'],"14,99€",-70%,0.0,"['Strategy', 'Grand Strategy', 'World War II',...",NaN,NaN,NaN,NaN
11022,https://store.steampowered.com/app/1161490/Mot...,MotoGP™20,2020-04-23,Milestone S.r.l.,"['Racing', 'Simulation', 'Sports']","19,99€",0%,1.0,"['Racing', 'Sports', 'Simulation', 'Motorbike'...",Very Positive,"2,245",Very Positive,20
11023,https://store.steampowered.com/app/1611430/The...,The Bridge Curse Road to Salvation,2022-08-24,SOFTSTAR ENTERTAINMENT,"['Action', 'Adventure', 'RPG']","16,79€",0%,1.0,"['Horror', 'First-Person', 'Puzzle', 'Explorat...",NaN,NaN,Very Positive,48
11024,https://store.steampowered.com/app/560370/SWAT...,SWAT 3: Tactical Game of the Year Edition,2001-10-10,Sierra,"['Action', 'Simulation']","9,99€",0%,0.0,"['Simulation', 'Action', 'Tactical', 'Violent'...",NaN,NaN,NaN,NaN

In [10]:
df_s.columns = ['link', 'name', 'release_date', 'developers', 'genre', 'price', 'discount', 'dlc', 'tags', 'rating', 'reviews_count', 'recent_rating', 'recent_reviews_count']
df_s.head()

,link,name,release_date,developers,genre,price,discount,dlc,tags,rating,reviews_count,recent_rating,recent_reviews_count
0,https://store.steampowered.com/app/730/Counter...,Counter-Strike 2,2012-08-21,Valve,"['Action', 'Free To Play']",Free To Play,0%,1.0,"['FPS', 'Shooter', 'Multiplayer', 'Competitive...",Very Positive,"9,521,157",Mostly Positive,"94,756"
1,https://store.steampowered.com/app/3321460/Cri...,Crimson Desert,NaN,Pearl Abyss,"['Экшены', 'Приключенческие игры']","69,99€",0%,1.0,"['Открытый мир', 'Экшен', 'Для одного игрока',...",Очень положительные,78 700,NaN,NaN
2,https://store.steampowered.com/app/2868840/Sla...,Slay the Spire 2,2026-03-05,Mega Crit,"['Indie', 'Strategy', 'Early Access']","22,99€",0%,0.0,"['Strategy', 'Roguelike', 'Card Game', 'Deckbu...",Very Positive,"98,132",Mostly Positive,"85,557"
3,https://store.steampowered.com/app/2050650/Res...,Resident Evil 4,2023-03-24,"CAPCOM Co., Ltd.","['Action', 'Adventure']","100,24€",-60%,27.0,"['Horror', 'Action', 'Survival Horror', 'Third...",Overwhelmingly Positive,"157,050",Overwhelmingly Positive,"7,371"
4,https://store.steampowered.com/app/1172470/Ape...,Apex Legends™,2020-11-04,Respawn,"['Action', 'Adventure', 'Free To Play']",Free To Play,0%,0.0,"['Free to Play', 'Battle Royale', 'Multiplayer...",Mixed,"1,040,934",Mixed,"8,265"

переименовала как в экселе у меня отображалось

In [17]:
params = {'key': API_KEY, 'search': 'Counter-Strike 2'}
response = requests.get('https://api.rawg.io/api/games', params=params)
res = response.json()

res

{'count': 23920,
 'next': 'https://api.rawg.io/api/games?key=b105bbeb82cb4401899b8fbd514e8913&page=2&search=Counter-Strike+2',
 'previous': None,
 'results': [{'slug': 'counter-strike-2-2',
   'name': 'Counter-Strike 2',
   'playtime': 0,
   'platforms': [{'platform': {'id': 4, 'name': 'PC', 'slug': 'pc'}},
    {'platform': {'id': 6, 'name': 'Linux', 'slug': 'linux'}}],
   'stores': [{'store': {'id': 1, 'name': 'Steam', 'slug': 'steam'}}],
   'released': '2023-09-27',
   'tba': False,
   'background_image': 'https://media.rawg.io/media/games/ec4/ec4b02bdb3eb5c6212992c19bc05697e.jpg',
   'rating': 3.57,
   'rating_top': 4,
   'ratings': [{'id': 4,
     'title': 'recommended',
     'count': 100,
     'percent': 46.3},
    {'id': 3, 'title': 'meh', 'count': 60, 'percent': 27.78},
    {'id': 5, 'title': 'exceptional', 'count': 34, 'percent': 15.74},
    {'id': 1, 'title': 'skip', 'count': 22, 'percent': 10.19}],
   'ratings_count': 210,
   'reviews_text_count': 3,
   'added': 486,
   'added_by_status': {'yet': 30,
    'owned': 113,
    'beaten': 69,
    'toplay': 17,
    'dropped': 165,
    'playing': 92},
   'metacritic': None,
   'suggestions_count': 343,
   'updated': '2026-04-02T17:15:26',
   'id': 965470,
   'score': '90.76185',
   'clip': None,
   'tags': [{'id': 40847,
     'name': 'Steam Achievements',
     'slug': 'steam-achievements',
     'language': 'eng',
     'games_count': 51708,
     'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'},
    {'id': 40836,
     'name': 'Full controller support',
     'slug': 'full-controller-support',
     'language': 'eng',
     'games_count': 24143,
     'image_background': 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg'},
    {'id': 8,
     'name': 'First-Person',
     'slug': 'first-person',
     'language': 'eng',
     'games_count': 37393,
     'image_background': 'https://media.rawg.io/media/games/120/1201a40e4364557b124392ee50317b99.jpg'},
    {'id': 30,
     'name': 'FPS',
     'slug': 'fps',
     'language': 'eng',
     'games_count': 14989,
     'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'},
    {'id': 49,
     'name': 'Difficult',
     'slug': 'difficult',
     'language': 'eng',
     'games_count': 14308,
     'image_background': 'https://media.rawg.io/media/games/48e/48e63bbddeddbe9ba81942772b156664.jpg'},
    {'id': 80,
     'name': 'Tactical',
     'slug': 'tactical',
     'language': 'eng',
     'games_count': 6619,
     'image_background': 'https://media.rawg.io/media/games/9bf/9bfac18ff678f41a4674250fa0e04a52.jpg'},
    {'id': 40852,
     'name': 'Steam Workshop',
     'slug': 'steam-workshop',
     'language': 'eng',
     'games_count': 1769,
     'image_background': 'https://media.rawg.io/media/games/7cf/7cfc9220b401b7a300e409e539c9afd5.jpg'},
    {'id': 70,
     'name': 'War',
     'slug': 'war',
     'language': 'eng',
     'games_count': 10101,
     'image_background': 'https://media.rawg.io/media/games/410/41033a495ce8f7fd4b0934bdb975f12a.jpg'},
    {'id': 131,
     'name': 'Fast-Paced',
     'slug': 'fast-paced',
     'language': 'eng',
     'games_count': 10821,
     'image_background': 'https://media.rawg.io/media/games/8e6/8e699e91cf77c2060b6d515e2135b1b1.jpg'},
    {'id': 81,
     'name': 'Military',
     'slug': 'military',
     'language': 'eng',
     'games_count': 2527,
     'image_background': 'https://media.rawg.io/media/games/106/1069e754e7e6012b0cf42b4b04704792.jpg'},
    {'id': 170,
     'name': 'Competitive',
     'slug': 'competitive',
     'language': 'eng',
     'games_count': 1313,
     'image_background': 'https://media.rawg.io/media/games/c07/c07e1c1e6908a2eeebd5dad0708abd01.jpg'},
    {'id': 40856,
     'name': 'Valve Anti-Cheat enabled',
     'slug': 'valve-anti-cheat-enabled',
     'language': 'eng',
     'games_count': 105,
     'image_background': 'https://media.rawg.io/media/games/78d/78dfae12fb8c5b16cd78648553071e0a.jpg'},
    {'id': 245,
     'name': 'Trading',
     'slug': 'trading',
     'language': 'eng',
     'games_count': 1490,
     'image_background': 'https://media.rawg.io/media/screenshots/64a/64a7870e16c1e90e254592baa8edba5e.jpg'},
    {'id': 2879,
     'name': 'esports',
     'slug': 'esports',
     'language': 'eng',
     'games_count': 892,
     'image_background': 'https://media.rawg.io/media/games/b67/b6769a1f19b6d6dd9216e3d4e56701b9.jpg'},
    {'id': 2809,
     'name': 'skins',
     'slug': 'skins',
     'language': 'eng',
     'games_count': 37,
     'image_background': 'https://media.rawg.io/media/screenshots/a00/a0082ef53d507c15dc8d66767591cc68.jpg'}],
   'esrb_rating': {'id': 4,
    'name': 'Mature',
    'slug': 'mature',
    'name_en': 'Mature',
    'name_ru': 'С 17 лет'},
   'user_game': None,
   'reviews_count': 216,
   'saturated_color': '0f0f0f',
   'dominant_color': '0f0f0f',
   'short_screenshots': [{'id': -1,
     'image': 'https://media.rawg.io/media/games/ec4/ec4b02bdb3eb5c6212992c19bc05697e.jpg'},
    {'id': 3919650,
     'image': 'https://media.rawg.io/media/screenshots/6af/6afb50645da07385de974521d52a55f4.jpg'},
    {'id': 3919651,
     'image': 'https://media.rawg.io/media/screenshots/cd4/cd4104f7561a63fc75144eb2e1b34bf2.jpg'},
    {'id': 3919652,
     'image': 'https://media.rawg.io/media/screenshots/083/083db13fd6d9352fa1109ad34f341d39.jpg'},
    {'id': 3919653,
     'image': 'https://media.rawg.io/media/screenshots/6ec/6ec9c109aae6f73e7cca7242864be069.jpg'},
    {'id': 3919654,
     'image': 'https://media.rawg.io/media/screenshots/618/618152fd1ad2f7416676639fb6c7267e.jpg'},
    {'id': 3919655,
     'image': 'https://media.rawg.io/media/screenshots/8f2/8f25913636c4dbe9a557776d22580f0e.jpg'}],
   'parent_platforms': [{'platform': {'id': 1, 'name': 'PC', 'slug': 'pc'}},
    {'platform': {'id': 6, 'name': 'Linux', 'slug': 'linux'}}],
   'genres': [{'id': 2, 'name': 'Shooter', 'slug': 'shooter'}]},
  {'slug': 'counter-strike',
   'name': 'Counter-Strike',
   'playtime': 3,
   'platforms': [{'platform': {'id': 4, 'name': 'PC', 'slug': 'pc'}},
    {'platform': {'id': 5, 'name': 'macOS', 'slug': 'macos'}},
    {'platform': {'id': 6, 'name': 'Linux', 'slug': 'linux'}},
    {'platform': {'id': 80, 'name': 'Xbox', 'slug': 'xbox-old'}}],
   'stores': [{'store': {'id': 1, 'name': 'Steam', 'slug': 'steam'}}],
   'released': '2000-11-01',
   'tba': False,
   'background_image': 'https://media.rawg.io/media/games/9c4/9c47f320eb73c9a02d462e12f6206b26.jpg',
   'rating': 4.06,
   'rating_top': 4,
   'ratings': [{'id': 4,
     'title': 'recommended',
     'count': 774,
     'percent': 46.65},
    {'id': 5, 'title': 'exceptional', 'count': 588, 'percent': 35.44},
    {'id': 3, 'title': 'meh', 'count': 198, 'percent': 11.93},
    {'id': 1, 'title': 'skip', 'count': 99, 'percent': 5.97}],
   'ratings_count': 1652,
   'reviews_text_count': 5,
   'added': 9315,
   'added_by_status': {'yet': 158,
    'owned': 7035,
    'beaten': 952,
    'toplay': 23,
    'dropped': 1096,
    'playing': 51},
   'metacritic': 88,
   'suggestions_count': 502,
   'updated': '2026-04-05T11:40:30',
   'id': 19301,
   'score': '44.541145',
   'clip': None,
   'tags': [{'id': 42417,
     'name': 'Экшен',
     'slug': 'ekshen',
     'language': 'rus',
     'games_count': 50552,
     'image_background': 'https://media.rawg.io/media/games/562/562553814dd54e001a541e4ee83a591c.jpg'},
    {'id': 7,
     'name': 'Multiplayer',
     'slug': 'multiplayer',
     'language': 'eng',
     'games_count': 42553,
     'image_background': 'https://media.rawg.io/media/games/587/587588c64afbff80e6f444eb2e46f9da.jpg'},
    {'id': 42425,
     'name': 'Для нескольких игроков',
     'slug': 'dlia-neskolkikh-igrokov',
     'language': 'rus',
     'games_count': 12936,
     'image_background': 'https://media.rawg.io/media/games/157/15742f2f67eacff546738e1ab5c19d20.jpg'},
    {'id': 42421,
     'name': 'Стратегия',
     'slug': 'strategiia',
     'language': 'rus',
     'games_count': 24810,
     'image_background': 'https://media.rawg.io/media/games/238/2383a172b4d50a7b44e07980eb7141ea.jpg'},
    {'id': 42428,
     'name': 'Шутер',
     'slug': 'shuter',
     'language': 'rus',
     'games_count': 11966,
     'image_background': 'https://media.rawg.io/media/games/490/49016e06ae2103881ff6373248843069.jpg'},
    {'id': 42429,
     'name': 'От первого лица',
     'slug': 'ot-pervogo-litsa',
     'language': 'rus',
     'games_count': 16469,
     'image_background': 'https://media.rawg.io/media/games/7cf/7cfc9220b401b7a300e409e539c9afd5.jpg'},
    {'id': 8,
     'name': 'First-Person',
     'slug': 'first-person',
     'language': 'eng',
     'games_count': 37393,
     'image_background': 'https://media.rawg.io/media/games/120/1201a40e4364557b124392ee50317b99.jpg'},
    {'id': 42435,
     'name': 'Шедевр',
     'slug': 'shedevr',
     'language': 'rus',
     'games_count': 1059,
     'image_background': 'https://media.rawg.io/media/games/310/3106b0e012271c5ffb16497b070be739.jpg'},
    {'id': 30,
     'name': 'FPS',
     'slug': 'fps',
     'language': 'eng',
     'games_count': 14989,
     'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'},
    {'id': 42427,
     'name': 'Шутер от первого лица',
     'slug': 'shuter-ot-pervogo-litsa',
     'language': 'rus',
     'games_count': 6971,
     'image_background': 'https://media.rawg.io/media/games/6c5/6c55e22185876626881b76c11922b073.jpg'},
    {'id': 42461,
     'name': 'Классика',
     'slug': 'klassika',
     'language': 'rus',
     'games_count': 1502,
     'image_background': 'https://media.rawg.io/media/games/62c/62c7c8b28a27b83680b22fb9d33fc619.jpg'},
    {'id': 193,
     'name': 'Classic',
     'slug': 'classic',
     'language': 'eng',
     'games_count': 1839,
     'image_background': 'https://media.rawg.io/media/games/9c4/9c47f320eb73c9a02d462e12f6206b26.jpg'},
    {'id': 42452,
     'name': 'Выживание',
     'slug': 'vyzhivanie',
     'language': 'rus',
     'games_count': 8282,
     'image_background': 'https://media.rawg.io/media/games/15c/15c95a4915f88a3e89c821526afe05fc.jpg'},
    {'id': 1,
     'name': 'Survival',
     'slug': 'survival',
     'language': 'eng',
     'games_count': 10834,
     'image_background': 'https://media.rawg.io/media/games/9dd/9ddabb34840ea9227556670606cf8ea3.jpg'},
    {'id': 42436,
     'name': 'Тактика',
     'slug': 'taktika',
     'language': 'rus',
     'games_count': 5243,
     'image_background': 'https://media.rawg.io/media/games/8bd/8bd24e3c15354a9555bb1437fe555a69.jpg'},
    {'id': 80,
     'name': 'Tactical',
     'slug': 'tactical',
     'language': 'eng',
     'games_count': 6619,
     'image_background': 'https://media.rawg.io/media/games/9bf/9bfac18ff678f41a4674250fa0e04a52.jpg'},
    {'id': 157,
     'name': 'PvP',
     'slug': 'pvp',
     'language': 'eng',
     'games_count': 12047,
     'image_background': 'https://media.rawg.io/media/games/e4a/e4ab7f784bdc38c76ce6e4cef9715d18.jpg'},
    {'id': 42434,
     'name': 'Игрок против игрока',
     'slug': 'igrok-protiv-igroka',
     'language': 'rus',
     'games_count': 7217,
     'image_background': 'https://media.rawg.io/media/games/736/73619bd336c894d6941d926bfd563946.jpg'},
    {'id': 11,
     'name': 'Team-Based',
     'slug': 'team-based',
     'language': 'eng',
     'games_count': 2072,
     'image_background': 'https://media.rawg.io/media/games/cc7/cc77035eb972f179f5090ee2a0fabd99.jpg'},
    {'id': 42450,
     'name': 'Командная',
     'slug': 'komandnaia',
     'language': 'rus',
     'games_count': 1772,
     'image_background': 'https://media.rawg.io/media/games/1bd/1bd2657b81eb0c99338120ad444b24ff.jpg'},
    {'id': 42476,
     'name': 'Соревновательная',
     'slug': 'sorevnovatelnaia',
     'language': 'rus',
     'games_count': 1117,
     'image_background': 'https://media.rawg.io/media/games/234/23410661770ae13eac11066980834367.jpg'},
    {'id': 42431,
     'name': 'Военные действия',
     'slug': 'voennye-deistviia',
     'language': 'rus',
     'games_count': 2511,
     'image_background': 'https://media.rawg.io/media/games/106/1069e754e7e6012b0cf42b4b04704792.jpg'},
    {'id': 81,
     'name': 'Military',
     'slug': 'military',
     'language': 'eng',
     'games_count': 2527,
     'image_background': 'https://media.rawg.io/media/games/106/1069e754e7e6012b0cf42b4b04704792.jpg'},
    {'id': 170,
     'name': 'Competitive',
     'slug': 'competitive',
     'language': 'eng',
     'games_count': 1313,
     'image_background': 'https://media.rawg.io/media/games/c07/c07e1c1e6908a2eeebd5dad0708abd01.jpg'},
    {'id': 40856,
     'name': 'Valve Anti-Cheat enabled',
     'slug': 'valve-anti-cheat-enabled',
     'language': 'eng',
     'games_count': 105,
     'image_background': 'https://media.rawg.io/media/games/78d/78dfae12fb8c5b16cd78648553071e0a.jpg'},
    {'id': 42484,
     'name': '90-е',
     'slug': '90-e',
     'language': 'rus',
     'games_count': 4123,
     'image_background': 'https://media.rawg.io/media/screenshots/b04/b042f8a7d3d9f8fe61d5af5d47ab6088.jpg'},
    {'id': 42512,
     'name': 'Олдскул',
     'slug': 'oldskul',
     'language': 'rus',
     'games_count': 5372,
     'image_background': 'https://media.rawg.io/media/games/abd/abdb7e589f0a8ccd36c0582673120b1e.jpg'},
    {'id': 243,
     'name': "1990's",
     'slug': '1990s',
     'language': 'eng',
     'games_count': 4028,
     'image_background': 'https://media.rawg.io/media/games/2f2/2f2eb93e32d400677b0b27f4686f7b4f.jpg'},
    {'id': 278,
     'name': 'Assassin',
     'slug': 'assassin',
     'language': 'eng',
     'games_count': 962,
     'image_background': 'https://media.rawg.io/media/games/0bc/0bcc108295a244b488d5c25f7d867220.jpg'},
    {'id': 42440,
     'name': 'Ассассины',
     'slug': 'assassiny',
     'language': 'rus',
     'games_count': 480,
     'image_background': 'https://media.rawg.io/media/games/233/233cdc08cce0228f6f35222eca3bff92.jpg'},
    {'id': 42588,
     'name': 'Киберспорт',
     'slug': 'kibersport',
     'language': 'rus',
     'games_count': 967,
     'image_background': 'https://media.rawg.io/media/screenshots/54f/54fcf1a626faa92afa3f5d2834dbc5ce.jpg'},
    {'id': 224,
     'name': '1980s',
     'slug': '1980s',
     'language': 'eng',
     'games_count': 3428,
     'image_background': 'https://media.rawg.io/media/games/c64/c64d2f63cabeab9126693b7d39539c8d.jpg'},
    {'id': 186,
     'name': 'Ninja',
     'slug': 'ninja',
     'language': 'eng',
     'games_count': 2513,
     'image_background': 'https://media.rawg.io/media/screenshots/033/033f9667f8d25eb544f600429f145b14.jpg'},
    {'id': 42633,
     'name': 'Набор очков',
     'slug': 'nabor-ochkov',
     'language': 'rus',
     'games_count': 3988,
     'image_background': 'https://media.rawg.io/media/screenshots/7b8/7b87220e0dbbc130f0cf7a50dd5f52fb.jpg'},
    {'id': 54,
     'name': 'Score Attack',
     'slug': 'score-attack',
     'language': 'eng',
     'games_count': 5486,
     'image_background': 'https://media.rawg.io/media/screenshots/8f5/8f5a4e32988c86cfc92e592c3b6c43ac.jpg'},
    {'id': 73,
     'name': 'e-sports',
     'slug': 'e-sports',
     'language': 'eng',
     'games_count': 80,
     'image_background': 'https://media.rawg.io/media/games/cc7/cc77035eb972f179f5090ee2a0fabd99.jpg'}],
   'esrb_rating': None,
   'user_game': None,
   'reviews_count': 1659,
   'saturated_color': '0f0f0f',
   'dominant_color': '0f0f0f',
   'short_screenshots': [{'id': -1,
     'image': 'https://media.rawg.io/media/games/9c4/9c47f320eb73c9a02d462e12f6206b26.jpg'},
    {'id': 179840,
     'image': 'https://media.rawg.io/media/screenshots/208/2087d6a9a20434bf4a28313b6ce09917.jpg'},
    {'id': 179841,
     'image': 'https://media.rawg.io/media/screenshots/58a/58a8a824744a5fe1c84e53ca9135f7ce.jpg'},
    {'id': 179842,
     'image': 'https://media.rawg.io/media/screenshots/8a8/8a8b23c4b62065c093f288e70ee9d9f2.jpg'},
    {'id': 179843,
     'image': 'https://media.rawg.io/media/screenshots/b3c/b3c5cf63e4558bb98b85eba830b90215.jpg'},
    {'id': 179844,
     'image': 'https://media.rawg.io/media/screenshots/a88/a8877e5cae44ef1ac8b36eeefce2ca34.jpg'},
    {'id': 179845,
     'image': 'https://media.rawg.io/media/screenshots/565/56570a92d4c85576f9ff1382c75c5ac4.jpg'}],
   'parent_platforms': [{'platform': {'id': 1, 'name': 'PC', 'slug': 'pc'}},
    {'platform': {'id': 3, 'name': 'Xbox', 'slug': 'xbox'}},
    {'platform': {'id': 5, 'name': 'Apple Macintosh', 'slug': 'mac'}},
    {'platform': {'id': 6, 'name': 'Linux', 'slug': 'linux'}}],
   'genres': [{'id': 2, 'name': 'Shooter', 'slug': 'shooter'},
    {'id': 4, 'name': 'Action', 'slug': 'action'}]},
  {'slug': 'counter-strike-source',
   'name': 'Counter-Strike: Source',
   'playtime': 7,
   'platforms': [{'platform': {'id': 4, 'name': 'PC', 'slug': 'pc'}},
    {'platform': {'id': 5, 'name': 'macOS', 'slug': 'macos'}},
    {'platform': {'id': 6, 'name': 'Linux', 'slug': 'linux'}}],
   'stores': [{'store': {'id': 1, 'name': 'Steam', 'slug': 'steam'}}],
   'released': '2004-11-01',
   'tba': False,
   'background_image': 'https://media.rawg.io/media/games/48e/48e63bbddeddbe9ba81942772b156664.jpg',
   'rating': 3.75,
   'rating_top': 4,
   'ratings': [{'id': 4,
     'title': 'recommended',
     'count': 804,
     'percent': 52.41},
    {'id': 3, 'title': 'meh', 'count': 309, 'percent': 20.14},
    {'id': 5, 'title': 'exceptional', 'count': 299, 'percent': 19.49},
    {'id': 1, 'title': 'skip', 'count': 122, 'percent': 7.95}],
   'ratings_count': 1528,
   'reviews_text_count': 3,
   'added': 9544,
   'added_by_status': {'yet': 189,
    'owned': 7599,
    'beaten': 690,
    'toplay': 21,
    'dropped': 988,
    'playing': 57},
   'metacritic': 88,
   'suggestions_count': 282,
   'updated': '2026-04-05T11:37:19',
   'id': 11934,
   'score': '37.487644',
   'clip': None,
   'tags': [{'id': 31,
     'name': 'Singleplayer',
     'slug': 'singleplayer',
     'language': 'eng',
     'games_count': 250824,
     'image_background': 'https://media.rawg.io/media/games/490/49016e06ae2103881ff6373248843069.jpg'},
    {'id': 42396,
     'name': 'Для одного игрока',
     'slug': 'dlia-odnogo-igroka',
     'language': 'rus',
     'games_count': 70693,
     'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'},
    {'id': 42417,
     'name': 'Экшен',
     'slug': 'ekshen',
     'language': 'rus',
     'games_count': 50552,
     'image_background': 'https://media.rawg.io/media/games/562/562553814dd54e001a541e4ee83a591c.jpg'},
    {'id': 40847,
     'name': 'Steam Achievements',
     'slug': 'steam-achievements',
     'language': 'eng',
     'games_count': 51708,
     'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'},
    {'id': 7,
     'name': 'Multiplayer',
     'slug': 'multiplayer',
     'language': 'eng',
     'games_count': 42553,
     'image_background': 'https://media.rawg.io/media/games/587/587588c64afbff80e6f444eb2e46f9da.jpg'},
    {'id': 40849,
     'name': 'Steam Cloud',
     'slug': 'steam-cloud',
     'language': 'eng',
     'games_count': 25733,
     'image_background': 'https://media.rawg.io/media/games/120/1201a40e4364557b124392ee50317b99.jpg'},
    {'id': 13,
     'name': 'Atmospheric',
     'slug': 'atmospheric',
     'language': 'eng',
     'games_count': 39707,
     'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'},
    {'id': 42425,
     'name': 'Для нескольких игроков',
     'slug': 'dlia-neskolkikh-igrokov',
     'language': 'rus',
     'games_count': 12936,
     'image_background': 'https://media.rawg.io/media/games/157/15742f2f67eacff546738e1ab5c19d20.jpg'},
    {'id': 42400,
     'name': 'Атмосфера',
     'slug': 'atmosfera',
     'language': 'rus',
     'games_count': 6083,
     'image_background': 'https://media.rawg.io/media/games/26d/26d4437715bee60138dab4a7c8c59c92.jpg'},

решила глянуть что будет по поиску одной игры(КЭЭЭЭСССГООО 2 была самой первой в нашем скраппинге стима)

In [18]:
df = pd.DataFrame(res['results'])
df

,slug,name,playtime,platforms,stores,released,tba,background_image,rating,rating_top,...,tags,esrb_rating,user_game,reviews_count,saturated_color,dominant_color,short_screenshots,parent_platforms,genres,community_rating
0,counter-strike-2-2,Counter-Strike 2,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-09-27,False,https://media.rawg.io/media/games/ec4/ec4b02bd...,3.57,4,...,"[{'id': 40847, 'name': 'Steam Achievements', '...","{'id': 4, 'name': 'Mature', 'slug': 'mature', ...",None,216,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 2, 'name': 'Shooter', 'slug': 'shooter'}]",NaN
1,counter-strike,Counter-Strike,3,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2000-11-01,False,https://media.rawg.io/media/games/9c4/9c47f320...,4.06,4,...,"[{'id': 42417, 'name': 'Экшен', 'slug': 'ekshe...",None,None,1659,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 2, 'name': 'Shooter', 'slug': 'shooter...",NaN
2,counter-strike-source,Counter-Strike: Source,7,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2004-11-01,False,https://media.rawg.io/media/games/48e/48e63bbd...,3.75,4,...,"[{'id': 31, 'name': 'Singleplayer', 'slug': 's...","{'id': 4, 'name': 'Mature', 'slug': 'mature', ...",None,1534,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 2, 'name': 'Shooter', 'slug': 'shooter'}]",NaN
3,counter-strike-2d,Counter-Strike 2D,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...",None,2005-01-01,False,https://media.rawg.io/media/screenshots/dbc/db...,3.14,4,...,[],None,None,7,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 11, 'name': 'Arcade', 'slug': 'arcade'}]",NaN
4,counter-strike-condition-zero,Counter-Strike: Condition Zero,1,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2004-03-01,False,https://media.rawg.io/media/games/8bd/8bd24e3c...,3.15,3,...,"[{'id': 31, 'name': 'Singleplayer', 'slug': 's...",None,None,832,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 4, 'name': 'Action', 'slug': 'action'}]",NaN
5,counter-strike-nexon-zombies,Counter-Strike Nexon: Zombies,1,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2014-09-23,False,https://media.rawg.io/media/screenshots/5ff/5f...,2.14,1,...,"[{'id': 31, 'name': 'Singleplayer', 'slug': 's...",None,None,237,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 40, 'name': 'Casual', 'slug': 'casual'...",NaN
6,counter-strike-global-offensive,Counter-Strike: Global Offensive,64,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2012-08-21,False,https://media.rawg.io/media/games/736/73619bd3...,3.57,4,...,"[{'id': 42417, 'name': 'Экшен', 'slug': 'ekshe...","{'id': 4, 'name': 'Mature', 'slug': 'mature', ...",None,3672,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 2, 'name': 'Shooter', 'slug': 'shooter'}]",NaN
7,counter-strike-condition-zero-deleted-scenes,Counter-Strike: Condition Zero Deleted Scenes,1,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2004-03-23,False,https://media.rawg.io/media/screenshots/9fd/9f...,2.88,4,...,"[{'id': 66667, 'name': 'cs', 'slug': 'cs', 'la...","{'id': 4, 'name': 'Mature', 'slug': 'mature', ...",None,180,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 2, 'name': 'Shooter', 'slug': 'shooter'}]",NaN
8,counter-strike-neo,Counter-Strike Neo,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...",None,2005-10-27,False,https://media.rawg.io/media/screenshots/606/60...,0.00,0,...,[],None,None,3,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 4, 'name': 'Action', 'slug': 'action'}]",0.0
9,sudden-strike-2-gold,Sudden Strike 2 Gold,1,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2002-08-29,False,https://media.rawg.io/media/screenshots/62d/62...,3.81,4,...,"[{'id': 31, 'name': 'Singleplayer', 'slug': 's...","{'id': 1, 'name': 'Everyone', 'slug': 'everyon...",None,26,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 10, 'name': 'Strategy', 'slug': 'strat...",NaN
10,igi-2-covert-strike,I.G.I. 2: Covert Strike,1,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 5, 'name': 'GOG', 'slug': 'g...",2003-02-25,False,https://media.rawg.io/media/games/2f6/2f632bc8...,3.73,4,...,"[{'id': 31, 'name': 'Singleplayer', 'slug': 's...","{'id': 4, 'name': 'Mature', 'slug': 'mature', ...",None,66,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 2, 'name': 'Shooter', 'slug': 'shooter...",NaN
11,counter-strike-unreal,Counter-Strike Unreal,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 9, 'name': 'itch.io', 'slug'...",2022-09-05,False,https://media.rawg.io/media/screenshots/89d/89...,0.00,0,...,"[{'id': 7, 'name': 'Multiplayer', 'slug': 'mul...",None,None,0,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 2, 'name': 'Shooter', 'slug': 'shooter'}]",0.0
12,counter-strike-source-2,Counter-Strike Source,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 9, 'name': 'itch.io', 'slug'...",2020-06-04,False,https://media.rawg.io/media/screenshots/530/53...,3.22,5,...,"[{'id': 677, 'name': 'evolution', 'slug': 'evo...",None,None,9,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 4, 'name': 'Action', 'slug': 'action'}]",NaN
13,dust-2-minecraft-counter-strike,Dust 2 - Minecraft Counter-strike,0,"[{'platform': {'id': 171, 'name': 'Web', 'slug...","[{'store': {'id': 9, 'name': 'itch.io', 'slug'...",2019-08-16,False,https://media.rawg.io/media/screenshots/175/17...,0.00,0,...,"[{'id': 177, 'name': 'Voxel', 'slug': 'voxel',...",None,None,0,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 14, 'name': 'Web', 'slug'...","[{'id': 2, 'name': 'Shooter', 'slug': 'shooter...",0.0
14,counter-strike-20,Counter-Strike: 2.0,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 9, 'name': 'itch.io', 'slug'...",2020-05-23,False,https://media.rawg.io/media/screenshots/587/58...,0.00,0,...,[],None,None,1,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 2, 'name': 'Shooter', 'slug': 'shooter'}]",0.0
15,infinium-strike,Infinium Strike,5,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2016-07-13,False,https://media.rawg.io/media/screenshots/eef/ee...,2.00,1,...,"[{'id': 31, 'name': 'Singleplayer', 'slug': 's...",None,None,6,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 40, 'name': 'Casual', 'slug': 'casual'...",NaN
16,jungle-strike,Jungle Strike,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...",None,1993-01-01,False,https://media.rawg.io/media/games/a49/a493b805...,4.01,4,...,"[{'id': 31, 'name': 'Singleplayer', 'slug': 's...","{'id': 2, 'name': 'Everyone 10+', 'slug': 'eve...",None,69,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 11, 'name': 'Arcade', 'slug': 'arcade'...",NaN
17,counter-fpsshooter-strike-war,Counter FPS:Shooter Strike War,0,"[{'platform': {'id': 3, 'name': 'iOS', 'slug':...","[{'store': {'id': 4, 'name': 'App Store', 'slu...",2018-06-09,False,https://media.rawg.io/media/screenshots/550/55...,0.00,0,...,"[{'id': 67, 'name': 'Management', 'slug': 'man...","{'id': 4, 'name': 'Mature', 'slug': 'mature', ...",None,0,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 4, 'name': 'iOS', 'slug':...","[{'id': 10, 'name': 'Strategy', 'slug': 'strat...",0.0
18,counter-strike-modern-warfare,Counter-Strike Modern Warfare,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 9, 'name': 'itch.io', 'slug'...",2019-07-31,False,https://media.rawg.io/media/screenshots/41e/41...,0.00,0,...,"[{'id': 8, 'name': 'First-Person', 'slug': 'fi...",None,None,0,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 2, 'name': 'Shooter', 'slug': 'shooter...",0.0
19,crash-bandicoot-2,Crash Bandicoot 2: Cortex Strikes Back,0,"[{'platform': {'id': 27, 'name': 'PlayStation'...","[{'store': {'id': 3, 'name': 'PlayStation Stor...",1997-11-01,False,https://media.rawg.io/media/games/a84/a84dc498...,4.27,4,...,"[{'id': 31, 'name': 'Singleplayer', 'slug': 's...",None,None,616,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 2, 'name': 'PlayStation',...","[{'id': 83, 'name': 'Platformer', 'slug': 'pla...",NaN

куча всего находит, но понятно что надо брать самый первый. тк самый первый ответ это самое похожее, что находит поиск(короче как работает любой поиск в гугле итд)

как описала выше, решили для каждой игры, которую спарсили, подобрать признаки. но не очень приятно это делать около 11к раз, поэтому конечно же нам нужна функция

In [19]:
def rawg(game_name):
    params = {'key': API_KEY, 'search': game_name}
    response = requests.get('https://api.rawg.io/api/games', params=params)
    res = response.json()

    game = res['results'][0] #беру как раз самую первую выдачу
    return game

In [20]:
rawg('Counter-Strike 2')

{'slug': 'counter-strike-2-2',
 'name': 'Counter-Strike 2',
 'playtime': 0,
 'platforms': [{'platform': {'id': 4, 'name': 'PC', 'slug': 'pc'}},
  {'platform': {'id': 6, 'name': 'Linux', 'slug': 'linux'}}],
 'stores': [{'store': {'id': 1, 'name': 'Steam', 'slug': 'steam'}}],
 'released': '2023-09-27',
 'tba': False,
 'background_image': 'https://media.rawg.io/media/games/ec4/ec4b02bdb3eb5c6212992c19bc05697e.jpg',
 'rating': 3.57,
 'rating_top': 4,
 'ratings': [{'id': 4, 'title': 'recommended', 'count': 100, 'percent': 46.3},
  {'id': 3, 'title': 'meh', 'count': 60, 'percent': 27.78},
  {'id': 5, 'title': 'exceptional', 'count': 34, 'percent': 15.74},
  {'id': 1, 'title': 'skip', 'count': 22, 'percent': 10.19}],
 'ratings_count': 210,
 'reviews_text_count': 3,
 'added': 486,
 'added_by_status': {'yet': 30,
  'owned': 113,
  'beaten': 69,
  'toplay': 17,
  'dropped': 165,
  'playing': 92},
 'metacritic': None,
 'suggestions_count': 343,
 'updated': '2026-04-02T17:15:26',
 'id': 965470,
 'score': '90.76193',
 'clip': None,
 'tags': [{'id': 40847,
   'name': 'Steam Achievements',
   'slug': 'steam-achievements',
   'language': 'eng',
   'games_count': 51708,
   'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'},
  {'id': 40836,
   'name': 'Full controller support',
   'slug': 'full-controller-support',
   'language': 'eng',
   'games_count': 24143,
   'image_background': 'https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg'},
  {'id': 8,
   'name': 'First-Person',
   'slug': 'first-person',
   'language': 'eng',
   'games_count': 37393,
   'image_background': 'https://media.rawg.io/media/games/120/1201a40e4364557b124392ee50317b99.jpg'},
  {'id': 30,
   'name': 'FPS',
   'slug': 'fps',
   'language': 'eng',
   'games_count': 14989,
   'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'},
  {'id': 49,
   'name': 'Difficult',
   'slug': 'difficult',
   'language': 'eng',
   'games_count': 14308,
   'image_background': 'https://media.rawg.io/media/games/48e/48e63bbddeddbe9ba81942772b156664.jpg'},
  {'id': 80,
   'name': 'Tactical',
   'slug': 'tactical',
   'language': 'eng',
   'games_count': 6619,
   'image_background': 'https://media.rawg.io/media/games/9bf/9bfac18ff678f41a4674250fa0e04a52.jpg'},
  {'id': 40852,
   'name': 'Steam Workshop',
   'slug': 'steam-workshop',
   'language': 'eng',
   'games_count': 1769,
   'image_background': 'https://media.rawg.io/media/games/7cf/7cfc9220b401b7a300e409e539c9afd5.jpg'},
  {'id': 70,
   'name': 'War',
   'slug': 'war',
   'language': 'eng',
   'games_count': 10101,
   'image_background': 'https://media.rawg.io/media/games/410/41033a495ce8f7fd4b0934bdb975f12a.jpg'},
  {'id': 131,
   'name': 'Fast-Paced',
   'slug': 'fast-paced',
   'language': 'eng',
   'games_count': 10821,
   'image_background': 'https://media.rawg.io/media/games/8e6/8e699e91cf77c2060b6d515e2135b1b1.jpg'},
  {'id': 81,
   'name': 'Military',
   'slug': 'military',
   'language': 'eng',
   'games_count': 2527,
   'image_background': 'https://media.rawg.io/media/games/106/1069e754e7e6012b0cf42b4b04704792.jpg'},
  {'id': 170,
   'name': 'Competitive',
   'slug': 'competitive',
   'language': 'eng',
   'games_count': 1313,
   'image_background': 'https://media.rawg.io/media/games/c07/c07e1c1e6908a2eeebd5dad0708abd01.jpg'},
  {'id': 40856,
   'name': 'Valve Anti-Cheat enabled',
   'slug': 'valve-anti-cheat-enabled',
   'language': 'eng',
   'games_count': 105,
   'image_background': 'https://media.rawg.io/media/games/78d/78dfae12fb8c5b16cd78648553071e0a.jpg'},
  {'id': 245,
   'name': 'Trading',
   'slug': 'trading',
   'language': 'eng',
   'games_count': 1490,
   'image_background': 'https://media.rawg.io/media/screenshots/64a/64a7870e16c1e90e254592baa8edba5e.jpg'},
  {'id': 2879,
   'name': 'esports',
   'slug': 'esports',
   'language': 'eng',
   'games_count': 892,
   'image_background': 'https://media.rawg.io/media/games/b67/b6769a1f19b6d6dd9216e3d4e56701b9.jpg'},
  {'id': 2809,
   'name': 'skins',
   'slug': 'skins',
   'language': 'eng',
   'games_count': 37,
   'image_background': 'https://media.rawg.io/media/screenshots/a00/a0082ef53d507c15dc8d66767591cc68.jpg'}],
 'esrb_rating': {'id': 4,
  'name': 'Mature',
  'slug': 'mature',
  'name_en': 'Mature',
  'name_ru': 'С 17 лет'},
 'user_game': None,
 'reviews_count': 216,
 'saturated_color': '0f0f0f',
 'dominant_color': '0f0f0f',
 'short_screenshots': [{'id': -1,
   'image': 'https://media.rawg.io/media/games/ec4/ec4b02bdb3eb5c6212992c19bc05697e.jpg'},
  {'id': 3919650,
   'image': 'https://media.rawg.io/media/screenshots/6af/6afb50645da07385de974521d52a55f4.jpg'},
  {'id': 3919651,
   'image': 'https://media.rawg.io/media/screenshots/cd4/cd4104f7561a63fc75144eb2e1b34bf2.jpg'},
  {'id': 3919652,
   'image': 'https://media.rawg.io/media/screenshots/083/083db13fd6d9352fa1109ad34f341d39.jpg'},
  {'id': 3919653,
   'image': 'https://media.rawg.io/media/screenshots/6ec/6ec9c109aae6f73e7cca7242864be069.jpg'},
  {'id': 3919654,
   'image': 'https://media.rawg.io/media/screenshots/618/618152fd1ad2f7416676639fb6c7267e.jpg'},
  {'id': 3919655,
   'image': 'https://media.rawg.io/media/screenshots/8f2/8f25913636c4dbe9a557776d22580f0e.jpg'}],
 'parent_platforms': [{'platform': {'id': 1, 'name': 'PC', 'slug': 'pc'}},
  {'platform': {'id': 6, 'name': 'Linux', 'slug': 'linux'}}],
 'genres': [{'id': 2, 'name': 'Shooter', 'slug': 'shooter'}]}

нормально вернул мне данные об игре атлична. решила перепроверить и посмотреть, тк мне потом так легче и удобнее начинать вытаскивать из этого гейм

In [21]:
def rawg(game_name):
    params = {'key': API_KEY, 'search': game_name}
    response = requests.get('https://api.rawg.io/api/games', params=params)
    res = response.json()

    game = res['results'][0] #беру как раз самую первую выдачу
    rating = game['rating']
    reviews_count = game['reviews_count']
    playtime = game['playtime']
    platforms = game['platforms'] #хочу глянуть

    return rating, reviews_count, playtime, platforms

In [22]:
rawg('Counter-Strike 2')

(3.57,
 216,
 0,
 [{'platform': {'id': 4, 'name': 'PC', 'slug': 'pc'}},
  {'platform': {'id': 6, 'name': 'Linux', 'slug': 'linux'}}])

так ну да все ровные пацыки кроме платформс(что в целом было видно когда смотрела все ответы по поиску ксссс гооо два). это немного грустно тк кроме этого признака там еще бедовые. надо будет как то расчехлять

In [23]:
def rawg(game_name):
    params = {'key': API_KEY, 'search': game_name}
    response = requests.get('https://api.rawg.io/api/games', params=params)
    res = response.json()

    game = res['results'][0] #беру как раз самую первую выдачу
    rating = game['rating']
    reviews_count = game['reviews_count']
    playtime = game['playtime']
    platforms = [p['platform']['name'] for p in game['platforms']]

    return rating, reviews_count, playtime, platforms

я не знаю нужно ли это писать... но наверно хуже не будет
в общем честно скажу не могла вспомнить как работать с этим списком словарей, поэтому почитала тут о комплексных словарях https://metanit.com/python/tutorial/3.3.php
тут про list comprehension https://itcodik.com/article/list-comprehensions-python-rukovodstvo, https://metanit.com/python/tutorial/3.6.php

In [24]:
rawg('Counter-Strike 2')

(3.57, 216, 0, ['PC', 'Linux'])

работаеееет аатлично. использую для всех странных челиков

In [25]:
def rawg(game_name):
    params = {'key': API_KEY, 'search': game_name}
    response = requests.get('https://api.rawg.io/api/games', params=params)
    res = response.json()

    game = res['results'][0] #беру как раз самую первую выдачу
    rating = game['rating']
    reviews_count = game['reviews_count']
    playtime = game['playtime']
    platforms = [p['platform']['name'] for p in game['platforms']]
    stores = [s['store']['name'] for s in game['stores']]
    esrb_rating = game['esrb_rating']['name'] #рейтинг ток один вроде, поэтмоу просто пробираюсь к нэйм

    return rating, reviews_count, playtime, platforms, stores, esrb_rating

In [26]:
rawg('Counter-Strike 2')

(3.57, 216, 0, ['PC', 'Linux'], ['Steam'], 'Mature')

так ну на одной игре все ок работает, дальше надо запустить по всем 11к играм...

In [27]:
!pip3 install tqdm

Collecting tqdm
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm
Successfully installed tqdm-4.67.3

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip

захотелос прогресс бар  как на семинаре

In [28]:
from tqdm import tqdm

In [29]:
data = []

In [30]:
for name in tqdm(df_s['name']): 
    result = rawg(name)           
    data.append(result)

  0%|          | 1/11025 [00:21<66:00:11, 21.55s/it]

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [31]:
df_s['name'][1]

'Crimson Desert'

In [32]:
rawg('Crimson Desert')

TypeError: 'NoneType' object is not iterable

господи помоги пусто у нас там. забыла про пропуски совсем.. у нас же неидеальные данные. вообще везде же могут быть пропуски. поработать надо над функцией

In [37]:
def rawg(game_name):
    params = {'key': API_KEY, 'search': game_name}
    response = requests.get('https://api.rawg.io/api/games', params=params)
    res = response.json()

    game = res['results'][0] #беру как раз самую первую выдачу
    rating = game['rating']
    reviews_count = game['reviews_count']
    playtime = game['playtime']
    platforms = [p['platform']['name'] for p in game['platforms']] if game['platforms'] is not None else None
    stores = [s['store']['name'] for s in game['stores']] if game['stores'] is not None else None
    esrb_rating = game['esrb_rating']['name'] if game['esrb_rating'] is not None else None

    return rating, reviews_count, playtime, platforms, stores, esrb_rating

иф елс все в той же статье по List Comprehensions https://itcodik.com/article/list-comprehensions-python-rukovodstvo

In [38]:
rawg('Crimson Desert')

(3.68,
 19,
 0,
 ['PC', 'PlayStation 5', 'Xbox One', 'PlayStation 4', 'Xbox Series S/X'],
 None,
 None)

урааааааа

In [39]:
for name in tqdm(df_s['name']): 
    result = rawg(name)           
    data.append(result)

  1%|▏         | 142/11025 [06:40<8:32:01,  2.82s/it]

KeyboardInterrupt:

ужасно долго это просто беда бедовая. 30 игр за 3 минуты... мы будем почти 17 часов это грузить, у нас уже совсем мало времени

In [40]:
from concurrent.futures import ThreadPoolExecutor

об этой велитколепой бибилиотеке прочитала здесь https://habr.com/ru/companies/otus/articles/771346/ и здесь https://medium.com/@smrati.katiyar/introduction-to-concurrent-futures-in-python-009fe1d4592c

In [42]:
with ThreadPoolExecutor(max_workers=10) as executor:
    results = list(tqdm(executor.map(rawg, df_s['name']), total=len(df_s)))

  3%|▎         | 304/11025 [01:42<1:00:18,  2.96it/s]

IndexError: list index out of range

точняк мы же не гарантированно найдем все игрыыыы..ааааааааааааааа помогите

In [43]:
def rawg(game_name):
    params = {'key': API_KEY, 'search': game_name}
    response = requests.get('https://api.rawg.io/api/games', params=params)
    res = response.json()
    
    if not res['results']:
        return None
    else:
        game = res['results'][0] #беру как раз самую первую выдачу
        rating = game['rating']
        reviews_count = game['reviews_count']
        playtime = game['playtime']
        platforms = [p['platform']['name'] for p in game['platforms']] if game['platforms'] is not None else None 
        stores = [s['store']['name'] for s in game['stores']] if game['stores'] is not None else None
        esrb_rating = game['esrb_rating']['name'] if game['esrb_rating'] is not None else None

        return rating, reviews_count, playtime, platforms, stores, esrb_rating

In [44]:
rawg('Crimson Desert')

(3.68,
 19,
 0,
 ['PC', 'PlayStation 5', 'Xbox One', 'PlayStation 4', 'Xbox Series S/X'],
 None,
 None)

In [45]:
with ThreadPoolExecutor(max_workers=10) as executor:
    results = list(tqdm(executor.map(rawg, df_s['name']), total=len(df_s)))

  0%|          | 54/11025 [00:16<56:03,  3.26it/s]

ChunkedEncodingError: ('Connection broken: IncompleteRead(8766 bytes read, 1474 more expected)', IncompleteRead(8766 bytes read, 1474 more expected))

коллеги(со скраппинга) сказали добавить слип, повинуюсь. еще читала в статье, что там надо осторожно макс воркерс, снижу

In [46]:
from time import sleep

In [47]:
def rawg(game_name):
    sleep(0.2)
    params = {'key': API_KEY, 'search': game_name}
    response = requests.get('https://api.rawg.io/api/games', params=params)
    res = response.json()
    
    if not res['results']:
        return None
    else:
        game = res['results'][0] #беру как раз самую первую выдачу
        rating = game['rating']
        reviews_count = game['reviews_count']
        playtime = game['playtime']
        platforms = [p['platform']['name'] for p in game['platforms']] if game['platforms'] is not None else None 
        stores = [s['store']['name'] for s in game['stores']] if game['stores'] is not None else None
        esrb_rating = game['esrb_rating']['name'] if game['esrb_rating'] is not None else None

        return rating, reviews_count, playtime, platforms, stores, esrb_rating

In [48]:
with ThreadPoolExecutor(max_workers=5) as executor:
    results = list(tqdm(executor.map(rawg, df_s['name']), total=len(df_s)))

  7%|▋         | 735/11025 [08:49<2:03:28,  1.39it/s]

ChunkedEncodingError: ('Connection broken: IncompleteRead(6026 bytes read, 4214 more expected)', IncompleteRead(6026 bytes read, 4214 more expected))

.......

In [52]:
def rawg(game_name):
    sleep(0.5) #повышаюююююю слип
    try:
        params = {'key': API_KEY, 'search': game_name}
        response = requests.get('https://api.rawg.io/api/games', params=params)
        res = response.json()
    
        if not res['results']:
            return None
        else:
            game = res['results'][0] #беру как раз самую первую выдачу
            rating = game['rating']
            reviews_count = game['reviews_count']
            playtime = game['playtime']
            platforms = [p['platform']['name'] for p in game['platforms']] if game['platforms'] is not None else None 
            stores = [s['store']['name'] for s in game['stores']] if game['stores'] is not None else None
            esrb_rating = game['esrb_rating']['name'] if game['esrb_rating'] is not None else None

            return rating, reviews_count, playtime, platforms, stores, esrb_rating
    except:
        return None

In [53]:
with ThreadPoolExecutor(max_workers=5) as executor:
    results = list(tqdm(executor.map(rawg, df_s['name']), total=len(df_s)))

  5%|▌         | 584/11025 [09:20<2:47:08,  1.04it/s]

KeyboardInterrupt:

подумала "блин хотя бы пока подумаю над следующими эндпоинтами, не буду тратить время". посмотрела след эндпоинт как нам кажется самый важный "ачивментс" там нужен айдишник каждоый игры...

в общем решили что целесобразнее айди сразу собирать, тк снова это запускать как минимум на 3 часа(если не упадет)) это жесть будет

In [55]:
def rawg(game_name):
    sleep(0.5) #повышаюююююю слип
    try:
        params = {'key': API_KEY, 'search': game_name}
        response = requests.get('https://api.rawg.io/api/games', params=params)
        res = response.json()
    
        if not res['results']:
            return None
        else:
            game = res['results'][0] #беру как раз самую первую выдачу
            rating = game['rating']
            reviews_count = game['reviews_count']
            playtime = game['playtime']
            platforms = [p['platform']['name'] for p in game['platforms']] if game['platforms'] is not None else None 
            stores = [s['store']['name'] for s in game['stores']] if game['stores'] is not None else None
            esrb_rating = game['esrb_rating']['name'] if game['esrb_rating'] is not None else None
            id_games = game['id'] 

            return rating, reviews_count, playtime, platforms, stores, esrb_rating, id_games
    except:
        return None

In [56]:
with ThreadPoolExecutor(max_workers=5) as executor:
    results = list(tqdm(executor.map(rawg, df_s['name']), total=len(df_s)))

  2%|▏         | 263/11025 [03:47<2:35:06,  1.16it/s]

KeyboardInterrupt:

In [58]:
def rawg(game_name):
    sleep(0.5) #повышаюююююю слип
    try:
        params = {'key': API_KEY, 'search': game_name}
        response = requests.get('https://api.rawg.io/api/games', params=params)
        res = response.json()
    
        if not res['results']:
            return None
        else:
            game = res['results'][0] #беру как раз самую первую выдачу
            rating = game['rating']
            reviews_count = game['reviews_count']
            playtime = game['playtime']
            platforms = [p['platform']['name'] for p in game['platforms']] if game['platforms'] is not None else None 
            stores = [s['store']['name'] for s in game['stores']] if game['stores'] is not None else None
            esrb_rating = game['esrb_rating']['name'] if game['esrb_rating'] is not None else None
            id_games = game['id'] 
            metacritic = game['metacritic'] #забыли эту имбулю
            return rating, reviews_count, playtime, platforms, stores, esrb_rating, id_games, metacritic
    except:
        return None

In [59]:
with ThreadPoolExecutor(max_workers=5) as executor:
    results = list(tqdm(executor.map(rawg, df_s['name']), total=len(df_s)))

100%|██████████| 11025/11025 [2:07:37<00:00,  1.44it/s]

In [62]:
results[:3]

[(3.57, 216, 0, ['PC', 'Linux'], ['Steam'], 'Mature', 965470, None),
 (3.68,
  19,
  0,
  ['PC', 'PlayStation 5', 'Xbox One', 'PlayStation 4', 'Xbox Series S/X'],
  None,
  None,
  529829,
  None),
 (0.0,
  5,
  7,
  ['PC', 'macOS', 'Linux'],
  ['Steam'],
  'Everyone 10+',
  994601,
  None)]

In [64]:
df_r = pd.DataFrame(results, columns=['rating', 'reviews_count', 'playtime', 'platforms', 'stores', 'esrb_rating', 'id_games', 'metacritic'])
df_r.to_csv('rawg_results_endp1.csv')

In [69]:
df_r['id_games'] = pd.to_numeric(df_r['id_games'], errors='coerce').astype('Int64')

In [71]:
params = {'key': API_KEY}
response = requests.get(f'https://api.rawg.io/api/games/965470/achievements', params=params)
res = response.json()
res

{'count': 0, 'next': None, 'previous': None, 'results': []}

In [72]:
def achievements(id_games):
    sleep(0.5)
    try:
        params = {'key': API_KEY}
        response = requests.get(f'https://api.rawg.io/api/games/{id_games}/achievements', params=params)
        res = response.json()
        return id_games, res['count']
    except:
        return id_games, None

In [73]:
with ThreadPoolExecutor(max_workers=5) as executor:
    results_endp_achievements = list(tqdm(executor.map(achievements, df_r['id_games']), total=len(df_r)))

100%|██████████| 11025/11025 [1:20:27<00:00,  2.28it/s]

In [75]:
df_ach = pd.DataFrame(results_endp_achievements, columns=['id_games', 'achievements_count'])
df_ach.to_csv('rawg_endp_achievements.csv', index=False)

In [82]:
API_KEY = "44005021a33d4da69abe340824ea6ea1"

In [83]:
params = {'key': API_KEY}
response = requests.get('https://api.rawg.io/api/games/965470/development-team', params=params)
res = response.json()
res

{'count': 1,
 'next': None,
 'previous': None,
 'results': [{'id': 28,
   'name': 'Mike Morasky',
   'slug': 'mike-morasky',
   'image': 'https://media.rawg.io/media/persons/c7a/c7a93276d53a31fd6d0edfd69cba5d62.jpg',
   'image_background': 'https://media.rawg.io/media/screenshots/3ef/3efdab6fb509150efd600d40e35f02f6.jpg',
   'games_count': 15,
   'games': [{'id': 4200,
     'slug': 'portal-2',
     'name': 'Portal 2',
     'released': '2011-04-18',
     'tba': False,
     'background_image': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg',
     'rating': 4.58,
     'rating_top': 5,
     'ratings': [{'id': 5,
       'title': 'exceptional',
       'count': 4243,
       'percent': 69.03},
      {'id': 4, 'title': 'recommended', 'count': 1555, 'percent': 25.3},
      {'id': 3, 'title': 'meh', 'count': 185, 'percent': 3.01},
      {'id': 1, 'title': 'skip', 'count': 164, 'percent': 2.67}],
     'ratings_count': 6090,
     'reviews_text_count': 40,
     'added': 20874,
     'added_by_status': {'yet': 676,
      'owned': 13110,
      'beaten': 5865,
      'toplay': 412,
      'dropped': 647,
      'playing': 164},
     'metacritic': 95,
     'playtime': 11,
     'suggestions_count': 570,
     'updated': '2026-04-06T20:18:13',
     'user_game': None,
     'reviews_count': 6147,
     'saturated_color': '0f0f0f',
     'dominant_color': '0f0f0f',
     'platforms': [{'platform': {'id': 16,
        'name': 'PlayStation 3',
        'slug': 'playstation3',
        'image': None,
        'year_end': None,
        'year_start': None,
        'games_count': 3195,
        'image_background': 'https://media.rawg.io/media/games/7fa/7fa0b586293c5861ee32490e953a4996.jpg'},
       'released_at': '2011-04-18',
       'requirements_en': None,
       'requirements_ru': None},
      {'platform': {'id': 4,
        'name': 'PC',
        'slug': 'pc',
        'image': None,
        'year_end': None,
        'year_start': None,
        'games_count': 560648,
        'image_background': 'https://media.rawg.io/media/games/736/73619bd336c894d6941d926bfd563946.jpg'},
       'released_at': '2011-04-18',
       'requirements_en': None,
       'requirements_ru': {'minimum': 'Core 2 Duo/Athlon X2 2 ГГц,1 Гб памяти,GeForce 7600/Radeon X800,10 Гб на винчестере,интернет-соединение',
        'recommended': 'Core 2 Duo/Athlon X2 2.5 ГГц,2 Гб памяти,GeForce GTX 280/Radeon HD 2600,10 Гб на винчестере,интернет-соединение'}},
      {'platform': {'id': 14,
        'name': 'Xbox 360',
        'slug': 'xbox360',
        'image': None,
        'year_end': None,
        'year_start': None,
        'games_count': 2828,
        'image_background': 'https://media.rawg.io/media/games/5c0/5c0dd63002cb23f804aab327d40ef119.jpg'},
       'released_at': '2011-04-18',
       'requirements_en': None,
       'requirements_ru': None},
      {'platform': {'id': 6,
        'name': 'Linux',
        'slug': 'linux',
        'image': None,
        'year_end': None,
        'year_start': None,
        'games_count': 80386,
        'image_background': 'https://media.rawg.io/media/games/49c/49c3dfa4ce2f6f140cc4825868e858cb.jpg'},
       'released_at': '2011-04-18',
       'requirements_en': None,
       'requirements_ru': None},
      {'platform': {'id': 5,
        'name': 'macOS',
        'slug': 'macos',
        'image': None,
        'year_end': None,
        'year_start': None,
        'games_count': 108039,
        'image_background': 'https://media.rawg.io/media/games/d58/d588947d4286e7b5e0e12e1bea7d9844.jpg'},
       'released_at': '2011-04-18',
       'requirements_en': None,
       'requirements_ru': None},
      {'platform': {'id': 1,
        'name': 'Xbox One',
        'slug': 'xbox-one',
        'image': None,
        'year_end': None,
        'year_start': None,
        'games_count': 5739,
        'image_background': 'https://media.rawg.io/media/games/511/5118aff5091cb3efec399c808f8c598f.jpg'},
       'released_at': '2011-04-18',
       'requirements_en': None,
       'requirements_ru': None}],
     'parent_platforms': [{'platform': {'id': 1, 'name': 'PC', 'slug': 'pc'}},
      {'platform': {'id': 2, 'name': 'PlayStation', 'slug': 'playstation'}},
      {'platform': {'id': 3, 'name': 'Xbox', 'slug': 'xbox'}},
      {'platform': {'id': 5, 'name': 'Apple Macintosh', 'slug': 'mac'}},
      {'platform': {'id': 6, 'name': 'Linux', 'slug': 'linux'}}],
     'genres': [{'id': 2,
       'name': 'Shooter',
       'slug': 'shooter',
       'games_count': 59634,
       'image_background': 'https://media.rawg.io/media/games/b49/b4912b5dbfc7ed8927b65f05b8507f6c.jpg'},
      {'id': 7,
       'name': 'Puzzle',
       'slug': 'puzzle',
       'games_count': 97414,
       'image_background': 'https://media.rawg.io/media/games/942/9424d6bb763dc38d9378b488603c87fa.jpg'}],
     'stores': [{'id': 465889,
       'store': {'id': 2,
        'name': 'Xbox Store',
        'slug': 'xbox-store',
        'domain': 'microsoft.com',
        'games_count': 4938,
        'image_background': 'https://media.rawg.io/media/games/34b/34b1f1850a1c06fd971bc6ab3ac0ce0e.jpg'}},
      {'id': 13134,
       'store': {'id': 1,
        'name': 'Steam',
        'slug': 'steam',
        'domain': 'store.steampowered.com',
        'games_count': 123289,
        'image_background': 'https://media.rawg.io/media/games/34b/34b1f1850a1c06fd971bc6ab3ac0ce0e.jpg'}},
      {'id': 4526,
       'store': {'id': 3,
        'name': 'PlayStation Store',
        'slug': 'playstation-store',
        'domain': 'store.playstation.com',
        'games_count': 8075,
        'image_background': 'https://media.rawg.io/media/games/021/021c4e21a1824d2526f925eff6324653.jpg'}},
      {'id': 33916,
       'store': {'id': 7,
        'name': 'Xbox 360 Store',
        'slug': 'xbox360',
        'domain': 'marketplace.xbox.com',
        'games_count': 1915,
        'image_background': 'https://media.rawg.io/media/games/bc0/bc06a29ceac58652b684deefe7d56099.jpg'}}],
     'clip': None,
     'tags': [{'id': 31,
       'name': 'Singleplayer',
       'slug': 'singleplayer',
       'language': 'eng',
       'games_count': 250826,
       'image_background': 'https://media.rawg.io/media/games/618/618c2031a07bbff6b4f611f10b6bcdbc.jpg'},
      {'id': 40847,
       'name': 'Steam Achievements',
       'slug': 'steam-achievements',
       'language': 'eng',
       'games_count': 51709,
       'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'},
      {'id': 7,
       'name': 'Multiplayer',
       'slug': 'multiplayer',
       'language': 'eng',
       'games_count': 42553,
       'image_background': 'https://media.rawg.io/media/games/157/15742f2f67eacff546738e1ab5c19d20.jpg'},
      {'id': 40836,
       'name': 'Full controller support',
       'slug': 'full-controller-support',
       'language': 'eng',
       'games_count': 24144,
       'image_background': 'https://media.rawg.io/media/games/16b/16b1b7b36e2042d1128d5a3e852b3b2f.jpg'},
      {'id': 40849,
       'name': 'Steam Cloud',
       'slug': 'steam-cloud',
       'language': 'eng',
       'games_count': 25733,
       'image_background': 'https://media.rawg.io/media/games/198/1988a337305e008b41d7f536ce9b73f6.jpg'},
      {'id': 13,
       'name': 'Atmospheric',
       'slug': 'atmospheric',
       'language': 'eng',
       'games_count': 39707,
       'image_background': 'https://media.rawg.io/media/games/562/562553814dd54e001a541e4ee83a591c.jpg'},
      {'id': 7808,
       'name': 'steam-trading-cards',
       'slug': 'steam-trading-cards',
       'language': 'eng',
       'games_count': 7568,
       'image_background': 'https://media.rawg.io/media/games/e6d/e6de699bd788497f4b52e2f41f9698f2.jpg'},
      {'id': 18,
       'name': 'Co-op',
       'slug': 'co-op',
       'language': 'eng',
       'games_count': 14391,
       'image_background': 'https://media.rawg.io/media/games/6fc/6fcf4cd3b17c288821388e6085bb0fc9.jpg'},
      {'id': 118,
       'name': 'Story Rich',
       'slug': 'story-rich',
       'language': 'eng',
       'games_count': 27258,
       'image_background': 'https://media.rawg.io/media/games/960/960b601d9541cec776c5fa42a00bf6c4.jpg'},
      {'id': 411,
       'name': 'cooperative',
       'slug': 'cooperative',
       'language': 'eng',
       'games_count': 6588,
       'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'},
      {'id': 8,
       'name': 'First-Person',
       'slug': 'first-person',
       'language': 'eng',
       'games_count': 37394,
       'image_background': 'https://media.rawg.io/media/games/d82/d82990b9c67ba0d2d09d4e6fa88885a7.jpg'},
      {'id': 32,
       'name': 'Sci-fi',
       'slug': 'sci-fi',
       'language': 'eng',
       'games_count': 22068,
       'image_background': 'https://media.rawg.io/media/games/174/174fabfca02d5730531bab2153a7dfcb.jpg'},
      {'id': 30,
       'name': 'FPS',
       'slug': 'fps',
       'language': 'eng',
       'games_count': 14989,
       'image_background': 'https://media.rawg.io/media/games/1bd/1bd2657b81eb0c99338120ad444b24ff.jpg'},
      {'id': 9,
       'name': 'Online Co-Op',
       'slug': 'online-co-op',
       'language': 'eng',
       'games_count': 7681,
       'image_background': 'https://media.rawg.io/media/games/d2c/d2c74dacd89fd817c2deb625b01adb1a.jpg'},
      {'id': 4,
       'name': 'Funny',
       'slug': 'funny',
       'language': 'eng',
       'games_count': 28841,
       'image_background': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg'},
      {'id': 189,
       'name': 'Female Protagonist',
       'slug': 'female-protagonist',
       'language': 'eng',
       'games_count': 15546,
       'image_background': 'https://media.rawg.io/media/games/8e4/8e4de3f54ac659e08a7ba6a2b731682a.jpg'},
      {'id': 123,
       'name': 'Comedy',
       'slug': 'comedy',
       'language': 'eng',
       'games_count': 14864,
       'image_background': 'https://media.rawg.io/media/games/ffe/ffed87105b14f5beff72ff44a7793fd5.jpg'},
      {'id': 75,
       'name': 'Local Co-Op',
       'slug': 'local-co-op',
       'language': 'eng',
       'games_count': 6081,
       'image_background': 'https://media.rawg.io/media/games/424/424facd40f4eb1f2794fe4b4bb28a277.jpg'},
      {'id': 11669,
       'name': 'stats',
       'slug': 'stats',
       'language': 'eng',
       'games_count': 6039,
       'image_background': 'https://media.rawg.io/media/games/476/476178ef18ab0534771d099f51cdc694.jpg'},
      {'id': 40852,
       'name': 'Steam Workshop',
       'slug': 'steam-workshop',
       'language': 'eng',
       'games_count': 1769,
       'image_background': 'https://media.rawg.io/media/games/7cf/7cfc9220b401b7a300e409e539c9afd5.jpg'},
      {'id': 25,
       'name': 'Space',
       'slug': 'space',
       'language': 'eng',
       'games_count': 44238,
       'image_background': 'https://media.rawg.io/media/screenshots/bf7/bf71c819eace914e6c42ae3ecb667308.jpg'},
      {'id': 40838,
       'name': 'Includes level editor',
       'slug': 'includes-level-editor',
       'language': 'eng',
       'games_count': 2218,
       'image_background': 'https://media.rawg.io/media/games/7fa/7fa0b586293c5861ee32490e953a4996.jpg'},
      {'id': 40833,
       'name': 'Captions available',
       'slug': 'captions-available',
       'language': 'eng',
       'games_count': 1485,
       'image_background': 'https://media.rawg.io/media/games/fee/fee0100afd87b52bfbd33e26689fa26c.jpg'},
      {'id': 40834,
       'name': 'Commentary available',
       'slug': 'commentary-available',
       'language': 'eng',
       'games_count': 299,
       'image_background': 'https://media.rawg.io/media/games/df2/df20fd77db56ae7b0a26a7ff4baa9ccc.jpg'},
      {'id': 87,
       'name': 'Science',
       'slug': 'science',
       'language': 'eng',
       'games_count': 2009,
       'image_background': 'https://media.rawg.io/media/games/bda/bdab2603c0dc67268d0610449bc7df16.jpg'}],
     'esrb_rating': {'id': 2,
      'name': 'Everyone 10+',
      'slug': 'everyone-10-plus'},
     'short_screenshots': [{'id': -1,
       'image': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'},
      {'id': 99018,
       'image': 'https://media.rawg.io/media/screenshots/221/221a03c11e5ff9f765d62f60d4b4cbf5.jpg'},
      {'id': 99019,
       'image': 'https://media.rawg.io/media/screenshots/173/1737ff43c14f40294011a209b1012875.jpg'},
      {'id': 99020,
       'image': 'https://media.rawg.io/media/screenshots/b11/b11a2ae0664f0e8a1ef2346f99df26e1.jpg'},
      {'id': 99021,
       'image': 'https://media.rawg.io/media/screenshots/9b1/9b107a790909b31918ebe2f40547cc85.jpg'},
      {'id': 99022,
       'image': 'https://media.rawg.io/media/screenshots/d05/d058fc7f7fa6128916c311eb14267fed.jpg'},
      {'id': 99023,
       'image': 'https://media.rawg.io/media/screenshots/415/41543dcc12dffc8e97d85a56ad42cda8.jpg'}]},
    {'id': 4291,
     'slug': 'counter-strike-global-offensive',
     'name': 'Counter-Strike: Global Offensive',
     'released': '2012-08-21',
     'tba': False,
     'background_image': 'https://media.rawg.io/media/games/736/73619bd336c894d6941d926bfd563946.jpg',
     'rating': 3.57,
     'rating_top': 4,
     'ratings': [{'id': 4,
       'title': 'recommended',
       'count': 1712,
       'percent': 46.62},
      {'id': 3, 'title': 'meh', 'count': 947, 'percent': 25.79},
      {'id': 5, 'title': 'exceptional', 'count': 603, 'percent': 16.42},
      {'id': 1, 'title': 'skip', 'count': 410, 'percent': 11.17}],
     'ratings_count': 3635,
     'reviews_text_count': 28,
     'added': 18357,
     'added_by_status': {'yet': 267,
      'owned': 14098,
      'beaten': 1149,
      'toplay': 82,
      'dropped': 2127,
      'playing': 634},
     'metacritic': 81,
     'playtime': 64,
     'suggestions_count': 607,
     'updated': '2026-04-07T10:11:49',
     'user_game': None,
     'reviews_count': 3672,
     'saturated_color': '0f0f0f',
     'dominant_color': '0f0f0f',
     'platforms': [{'platform': {'id': 4,
        'name': 'PC',
        'slug': 'pc',
        'image': None,
        'year_end': None,
        'year_start': None,
        'games_count': 560648,
        'image_background': 'https://media.rawg.io/media/games/736/73619bd336c894d6941d926bfd563946.jpg'},
       'released_at': '2012-08-21',
       'requirements_en': {'minimum': '<strong>Minimum:</strong><br><ul class="bb_ul"><li><strong>OS:</strong> Windows® 7/Vista/XP<br></li><li><strong>Processor:</strong> Intel® Core™ 2 Duo E6600 or AMD Phenom™ X3 8750 processor or better<br></li><li><strong>Memory:</strong> 2 GB RAM<br></li><li><strong>Graphics:</strong> Video card must be 256 MB or more and should be a DirectX 9-compatible with support for Pixel Shader 3.0<br></li><li><strong>DirectX:</strong> Version 9.0c<br></li><li><strong>Storage:</strong> 15 GB available space</li></ul>'},
       'requirements_ru': {'minimum': 'Сore 2 Duo/Athlon x2 64 1.8 ГГц,2 Гб памяти,GeForce 8800/Radeon X9800,7.6 Гб на винчестере,интернет-соединение',
        'recommended': 'Core 2 Duo E6600/Phenom X3 8750,4 Гб памяти,GeForce 480 GTX/Radeon HD 6970,7.6 Гб на винчестере,интернет-соединение'}},
      {'platform': {'id': 6,
        'name': 'Linux',
        'slug': 'linux',
        'image': None,
        'year_end': None,
        'year_start': None,
        'games_count': 80386,
        'image_background': 'https://media.rawg.io/media/games/49c/49c3dfa4ce2f6f140cc4825868e858cb.jpg'},
       'released_at': '2012-08-21',
       'requirements_en': None,
       'requirements_ru': None},
      {'platform': {'id': 14,
        'name': 'Xbox 360',
        'slug': 'xbox360',
        'image': None,
        'year_end': None,
        'year_start': None,
        'games_count': 2828,
        'image_background': 'https://media.rawg.io/media/games/5c0/5c0dd63002cb23f804aab327d40ef119.jpg'},
       'released_at': '2012-08-21',
       'requirements_en': None,
       'requirements_ru': None},
      {'platform': {'id': 16,
        'name': 'PlayStation 3',
        'slug': 'playstation3',
        'image': None,
        'year_end': None,
        'year_start': None,
        'games_count': 3195,
        'image_background': 'https://media.rawg.io/media/games/7fa/7fa0b586293c5861ee32490e953a4996.jpg'},
       'released_at': '2012-08-21',
       'requirements_en': None,
       'requirements_ru': None}],
     'parent_platforms': [{'platform': {'id': 1, 'name': 'PC', 'slug': 'pc'}},
      {'platform': {'id': 2, 'name': 'PlayStation', 'slug': 'playstation'}},
      {'platform': {'id': 3, 'name': 'Xbox', 'slug': 'xbox'}},
      {'platform': {'id': 6, 'name': 'Linux', 'slug': 'linux'}}],
     'genres': [{'id': 2,
       'name': 'Shooter',
       'slug': 'shooter',
       'games_count': 59634,
       'image_background': 'https://media.rawg.io/media/games/b49/b4912b5dbfc7ed8927b65f05b8507f6c.jpg'}],
     'stores': [{'id': 4619,
       'store': {'id': 3,
        'name': 'PlayStation Store',
        'slug': 'playstation-store',
        'domain': 'store.playstation.com',
        'games_count': 8075,
        'image_background': 'https://media.rawg.io/media/games/021/021c4e21a1824d2526f925eff6324653.jpg'}},
      {'id': 11489,
       'store': {'id': 1,
        'name': 'Steam',
        'slug': 'steam',
        'domain': 'store.steampowered.com',
        'games_count': 123289,
        'image_background': 'https://media.rawg.io/media/games/34b/34b1f1850a1c06fd971bc6ab3ac0ce0e.jpg'}},
      {'id': 49169,
       'store': {'id': 7,
        'name': 'Xbox 360 Store',
        'slug': 'xbox360',
        'domain': 'marketplace.xbox.com',
        'games_count': 1915,
        'image_background': 'https://media.rawg.io/media/games/bc0/bc06a29ceac58652b684deefe7d56099.jpg'}}],
     'clip': None,
     'tags': [{'id': 40847,
       'name': 'Steam Achievements',
       'slug': 'steam-achievements',
       'language': 'eng',
       'games_count': 51709,
       'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'},
      {'id': 7,
       'name': 'Multiplayer',
       'slug': 'multiplayer',
       'language': 'eng',
       'games_count': 42553,
       'image_background': 'https://media.rawg.io/media/games/157/15742f2f67eacff546738e1ab5c19d20.jpg'},
      {'id': 40836,
       'name': 'Full controller support',
       'slug': 'full-controller-support',
       'language': 'eng',
       'games_count': 24144,
       'image_background': 'https://media.rawg.io/media/games/16b/16b1b7b36e2042d1128d5a3e852b3b2f.jpg'},
      {'id': 7808,
       'name': 'steam-trading-cards',
       'slug': 'steam-trading-cards',
       'language': 'eng',
       'games_count': 7568,
       'image_background': 'https://media.rawg.io/media/games/e6d/e6de699bd788497f4b52e2f41f9698f2.jpg'},
      {'id': 18,
       'name': 'Co-op',
       'slug': 'co-op',
       'language': 'eng',
       'games_count': 14391,
       'image_background': 'https://media.rawg.io/media/games/6fc/6fcf4cd3b17c288821388e6085bb0fc9.jpg'},
      {'id': 411,
       'name': 'cooperative',
       'slug': 'cooperative',
       'language': 'eng',
       'games_count': 6588,
       'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'},
      {'id': 8,
       'name': 'First-Person',
       'slug': 'first-person',
       'language': 'eng',
       'games_count': 37394,
       'image_background': 'https://media.rawg.io/media/games/d82/d82990b9c67ba0d2d09d4e6fa88885a7.jpg'},
      {'id': 30,
       'name': 'FPS',
       'slug': 'fps',
       'language': 'eng',
       'games_count': 14989,
       'image_background': 'https://media.rawg.io/media/games/1bd/1bd2657b81eb0c99338120ad444b24ff.jpg'},
      {'id': 9,
       'name': 'Online Co-Op',
       'slug': 'online-co-op',
       'language': 'eng',
       'games_count': 7681,

In [84]:
def dev_team(id_games):
    sleep(0.5)
    try:
        params = {'key': API_KEY}
        response = requests.get(f'https://api.rawg.io/api/games/{id_games}/development-team', params=params)
        res = response.json()
        return id_games, res['count']
    except:
        return id_games, None

In [85]:
dev_team(965470)

(965470, 1)

In [87]:
with ThreadPoolExecutor(max_workers=5) as executor:
    results_endp_devteam = list(tqdm(executor.map(dev_team, df_r['id_games']), total=len(df_r)))

100%|██████████| 11025/11025 [1:49:04<00:00,  1.68it/s]

In [88]:
df_devteam = pd.DataFrame(results_endp_devteam, columns=['id_games', 'dev_team_count'])
df_devteam.to_csv('rawg_devteam_endp.csv', index=False)

In [91]:
params = {'key': API_KEY}
response = requests.get('https://api.rawg.io/api/games/965470/game-series', params=params)
res = response.json()
res

{'count': 0, 'next': None, 'previous': None, 'results': []}

In [92]:
API_KEY = "0f022638c8da4d3ea857e11dfba95587"

In [93]:
def series (id_games):
    sleep(0.5)
    try:
        params = {'key': API_KEY}
        response = requests.get(f'https://api.rawg.io/api/games/{id_games}/game-series', params=params)
        res = response.json()
        return id_games, res['count']
    except:
        return id_games, None

In [94]:
with ThreadPoolExecutor(max_workers=5) as executor:
    results_g_series = list(tqdm(executor.map(series, df_r['id_games']), total=len(df_r)))

100%|██████████| 11025/11025 [2:08:14<00:00,  1.43it/s]

In [95]:
df_series = pd.DataFrame(results_g_series, columns=['id_games', 'series_count'])
df_series.to_csv('rawg_endp_g_series.csv', index=False)

In [96]:
df_r.head()

,rating,reviews_count,playtime,platforms,stores,esrb_rating,id_games,metacritic
0,3.57,216.0,0.0,"[PC, Linux]",[Steam],Mature,965470,NaN
1,3.68,19.0,0.0,"[PC, PlayStation 5, Xbox One, PlayStation 4, X...",None,NaN,529829,NaN
2,0.00,5.0,7.0,"[PC, macOS, Linux]",[Steam],Everyone 10+,994601,NaN
3,4.58,635.0,24.0,"[PC, PlayStation 5, PlayStation 4, Xbox Series...","[Steam, PlayStation Store]",Mature,795632,NaN
4,3.63,2439.0,5.0,"[PC, Xbox One, PlayStation 4, Nintendo Switch,...","[Steam, PlayStation Store, Xbox Store, Nintend...",Teen,290856,80.0

In [98]:
df_ach = pd.read_csv('rawg_endp_achievements.csv')

In [104]:
df_ach.head()

   id_games  achievements_count
0  965470.0                 0.0
1  529829.0                 0.0
2  994601.0                 0.0
3  795632.0                34.0
4  290856.0                12.0

In [105]:
df_ach['id_games'] = pd.to_numeric(df_r['id_games'], errors='coerce').astype('Int64')

In [106]:
df_ach.head()

   id_games  achievements_count
0    965470                 0.0
1    529829                 0.0
2    994601                 0.0
3    795632                34.0
4    290856                12.0

In [154]:
df_s[df_s.duplicated(subset='name')].size

377

In [151]:
df_r[df_r['id_games'] == 529829]

,rating,reviews_count,playtime,platforms,stores,esrb_rating,id_games,metacritic
1,3.68,19.0,0.0,"[PC, PlayStation 5, Xbox One, PlayStation 4, X...",None,NaN,529829,NaN
723,3.68,19.0,0.0,"[PC, PlayStation 5, Xbox One, PlayStation 4, X...",None,NaN,529829,NaN

In [145]:
df_final = df_r.merge(df_ach, on='id_games')

In [146]:
df_final.head()

,rating,reviews_count,playtime,platforms,stores,esrb_rating,id_games,metacritic,achievements_count
0,3.57,216.0,0.0,"[PC, Linux]",[Steam],Mature,965470,NaN,0.0
1,3.68,19.0,0.0,"[PC, PlayStation 5, Xbox One, PlayStation 4, X...",None,NaN,529829,NaN,0.0
2,3.68,19.0,0.0,"[PC, PlayStation 5, Xbox One, PlayStation 4, X...",None,NaN,529829,NaN,0.0
3,0.00,5.0,7.0,"[PC, macOS, Linux]",[Steam],Everyone 10+,994601,NaN,0.0
4,4.58,635.0,24.0,"[PC, PlayStation 5, PlayStation 4, Xbox Series...","[Steam, PlayStation Store]",Mature,795632,NaN,34.0

In [135]:
df_add = pd.read_csv('rawg_results_endp_dlc.csv')

In [136]:
df_add['id_games'] = pd.to_numeric(df_r['id_games'], errors='coerce').astype('Int64')

In [137]:
df_add.head()

   Unnamed: 0  id_games  a_count
0           0    965470      0.0
1           1    529829      0.0
2           2    994601      0.0
3           3    795632      0.0
4           4    290856     21.0

In [138]:
df_add = df_add.drop(columns=['Unnamed: 0'])

In [139]:
df_add.head()

   id_games  a_count
0    965470      0.0
1    529829      0.0
2    994601      0.0
3    795632      0.0
4    290856     21.0

In [147]:
df_final.head()

,rating,reviews_count,playtime,platforms,stores,esrb_rating,id_games,metacritic,achievements_count
0,3.57,216.0,0.0,"[PC, Linux]",[Steam],Mature,965470,NaN,0.0
1,3.68,19.0,0.0,"[PC, PlayStation 5, Xbox One, PlayStation 4, X...",None,NaN,529829,NaN,0.0
2,3.68,19.0,0.0,"[PC, PlayStation 5, Xbox One, PlayStation 4, X...",None,NaN,529829,NaN,0.0
3,0.00,5.0,7.0,"[PC, macOS, Linux]",[Steam],Everyone 10+,994601,NaN,0.0
4,4.58,635.0,24.0,"[PC, PlayStation 5, PlayStation 4, Xbox Series...","[Steam, PlayStation Store]",Mature,795632,NaN,34.0

In [148]:
df_final = df_final.merge(df_add, on='id_games')

In [155]:
df_final

,rating,reviews_count,playtime,platforms,stores,esrb_rating,id_games,metacritic,achievements_count,a_count
0,3.57,216.0,0.0,"[PC, Linux]",[Steam],Mature,965470,NaN,0.0,0.0
1,3.68,19.0,0.0,"[PC, PlayStation 5, Xbox One, PlayStation 4, X...",None,NaN,529829,NaN,0.0,0.0
2,3.68,19.0,0.0,"[PC, PlayStation 5, Xbox One, PlayStation 4, X...",None,NaN,529829,NaN,0.0,0.0
3,3.68,19.0,0.0,"[PC, PlayStation 5, Xbox One, PlayStation 4, X...",None,NaN,529829,NaN,0.0,0.0
4,3.68,19.0,0.0,"[PC, PlayStation 5, Xbox One, PlayStation 4, X...",None,NaN,529829,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
1292686,0.00,1.0,0.0,[PC],None,NaN,290006,NaN,NaN,NaN
1292687,0.00,0.0,1.0,[PC],"[Steam, itch.io]",NaN,519882,NaN,NaN,NaN
1292688,3.38,21.0,4.0,"[PC, Xbox One, PlayStation 4, Nintendo Switch]","[Steam, PlayStation Store, Xbox Store, Nintend...",Everyone,413881,NaN,NaN,NaN
1292689,0.00,2.0,3.0,"[PC, PlayStation 5, Xbox One, PlayStation 4, X...","[Steam, PlayStation Store, Xbox Store, Nintend...",Mature,840800,NaN,NaN,NaN
1292690,4.14,14.0,1.0,[PC],[Steam],NaN,22238,NaN,NaN,NaN

хотелось по красому смерджит, но дубликаты как то все портят. по логике должно контакт хорошо сработать, все таки по одному айди гейм шло все, плюс не хочется дубликаты чистить, так как айди эти пропорционально собирались датасету с играми, которые мы заскраппили со стима

In [156]:
df_final = pd.concat([df_r, df_ach['achievements_count'], df_add['a_count'], df_series['series_count'], df_devteam['dev_team_count']], axis=1)
df_final.head()

,rating,reviews_count,playtime,platforms,stores,esrb_rating,id_games,metacritic,achievements_count,a_count,series_count,dev_team_count
0,3.57,216.0,0.0,"[PC, Linux]",[Steam],Mature,965470,NaN,0.0,0.0,0.0,1.0
1,3.68,19.0,0.0,"[PC, PlayStation 5, Xbox One, PlayStation 4, X...",None,NaN,529829,NaN,0.0,0.0,0.0,0.0
2,0.00,5.0,7.0,"[PC, macOS, Linux]",[Steam],Everyone 10+,994601,NaN,0.0,0.0,1.0,1.0
3,4.58,635.0,24.0,"[PC, PlayStation 5, PlayStation 4, Xbox Series...","[Steam, PlayStation Store]",Mature,795632,NaN,34.0,0.0,28.0,7.0
4,3.63,2439.0,5.0,"[PC, Xbox One, PlayStation 4, Nintendo Switch,...","[Steam, PlayStation Store, Xbox Store, Nintend...",Teen,290856,80.0,12.0,21.0,1.0,3.0

In [157]:
df_final

,rating,reviews_count,playtime,platforms,stores,esrb_rating,id_games,metacritic,achievements_count,a_count,series_count,dev_team_count
0,3.57,216.0,0.0,"[PC, Linux]",[Steam],Mature,965470,NaN,0.0,0.0,0.0,1.0
1,3.68,19.0,0.0,"[PC, PlayStation 5, Xbox One, PlayStation 4, X...",None,NaN,529829,NaN,0.0,0.0,0.0,0.0
2,0.00,5.0,7.0,"[PC, macOS, Linux]",[Steam],Everyone 10+,994601,NaN,0.0,0.0,1.0,1.0
3,4.58,635.0,24.0,"[PC, PlayStation 5, PlayStation 4, Xbox Series...","[Steam, PlayStation Store]",Mature,795632,NaN,34.0,0.0,28.0,7.0
4,3.63,2439.0,5.0,"[PC, Xbox One, PlayStation 4, Nintendo Switch,...","[Steam, PlayStation Store, Xbox Store, Nintend...",Teen,290856,80.0,12.0,21.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
11020,0.00,1.0,0.0,[PC],None,NaN,290006,NaN,NaN,NaN,0.0,6.0
11021,0.00,0.0,1.0,[PC],"[Steam, itch.io]",NaN,519882,NaN,NaN,NaN,0.0,0.0
11022,3.38,21.0,4.0,"[PC, Xbox One, PlayStation 4, Nintendo Switch]","[Steam, PlayStation Store, Xbox Store, Nintend...",Everyone,413881,NaN,NaN,NaN,14.0,0.0
11023,0.00,2.0,3.0,"[PC, PlayStation 5, Xbox One, PlayStation 4, X...","[Steam, PlayStation Store, Xbox Store, Nintend...",Mature,840800,NaN,NaN,NaN,1.0,0.0
11024,4.14,14.0,1.0,[PC],[Steam],NaN,22238,NaN,NaN,NaN,0.0,0.0

ура ура

In [159]:
df_final.isnull().sum()

rating                  51
reviews_count           51
playtime                51
platforms               86
stores                 568
esrb_rating           7645
id_games                51
metacritic            7956
achievements_count    4328
a_count               1386
series_count           111
dev_team_count          54
dtype: int64